/* ============ RICETTARIO INIZIALE ============
 role: main (fonte proteica) | base (cereale/pasta/pane) | side (contorno) | scorta (sugo da freezer) | dolce
 protein: g per porzione (stime da tabelle di composizione, ±10%)
 months: mesi di stagione · dairy: contiene latticini animali · spicy: piccante (mai proposto)
 store (dolci): giorni in dispensa / giorni in frigo / mesi in freezer */
const LIB_VERSION=3;
const REPARTI=["Ortofrutta","Pesce","Frigo","Surgelati","Dispensa","Panetteria","Basi"];
function M(r){if(Array.isArray(r))return r;if(r==="all")return[1,2,3,4,5,6,7,8,9,10,11,12];const[a,b]=r.split("-").map(Number);const o=[];let m=a;for(;;){o.push(m);if(m===b)break;m=m%12+1}return o}
function I(list){return list.map(s=>{const[q,n,r]=s.split("|");return{q,n,r}})}
const LIB=[
/* ---------- BASI ---------- */
{id:"farro",name:"Farro perlato",role:"base",portions:5,protein:10,prepMin:5,cookMin:25,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["350 g|farro perlato|Dispensa"]),steps:["Sciacqua il farro.","Cuocilo 20–25 minuti in abbondante acqua salata in bollore.","Scolalo al dente, stendilo su un vassoio con un filo d'olio e fallo raffreddare al massimo un'ora.","Dividi in contenitori."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Bolle da solo: intanto prepari altro.",think:"Perché stenderlo invece di lasciarlo nello scolapasta? Pensa al centro di una montagnola calda.",
 draw:{vessel:"bowl",bowl:"#2F5F66",base:"#C9A56C",base2:"#B58E55",pieces:[{t:"grain",c:"#D8B983",n:130,s:.035}]}},
{id:"orzo",name:"Orzo perlato",role:"base",portions:5,protein:7,prepMin:5,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["350 g|orzo perlato|Dispensa"]),steps:["Sciacqua l'orzo.","Cuocilo 25–30 minuti in acqua salata.","Scola, stendi a raffreddare con un filo d'olio, dividi in contenitori."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Bolle da solo.",think:"Ricco di beta-glucani, le stesse fibre solubili dell'avena.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#D9C7A0",base2:"#C8B288",pieces:[{t:"grain",c:"#EADBB8",n:120,s:.035}]}},
{id:"riso",name:"Riso integrale",role:"base",portions:5,protein:5,prepMin:5,cookMin:35,equip:"fuochi",fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["350 g|riso integrale|Dispensa"]),steps:["Cuoci il riso 30–35 minuti in acqua salata.","Scolalo e stendilo subito su un vassoio: deve essere in frigo entro un'ora.","Quello che serve dopo il terzo giorno va in freezer."],
 cons:"Frigo 3 giorni, non 4. Freezer 3 mesi.",par:"Bolle da solo.",think:"Perché il riso ha un giorno in meno? Leggi la domanda su Bacillus cereus nella Guida frigo.",
 draw:{vessel:"bowl",bowl:"#3D4F5C",base:"#CDB893",base2:"#B9A27A",pieces:[{t:"grain",c:"#DCC9A4",n:140,s:.03}]}},
{id:"couscous",name:"Couscous integrale al limone",role:"base",portions:5,protein:9,prepMin:5,cookMin:5,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["350 g|couscous integrale|Dispensa","1|limone|Ortofrutta"]),steps:["Porta a bollore 400 ml d'acqua salata con un filo d'olio.","Versala sul couscous, copri e lascia 5 minuti.","Sgrana con una forchetta, aggiungi scorza e succo di limone."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Pronto in 5 minuti: fallo mentre il forno lavora.",think:"Il couscous è semola già precotta: per questo basta idratarlo.",
 draw:{vessel:"bowl",bowl:"#2F5F66",base:"#E6CB84",base2:"#D8B76A",pieces:[{t:"dot",c:"#F0DA9C",n:160,s:.012},{t:"leaf",c:"#4E8A3A",n:5,s:.06}]}},
{id:"pasta",name:"Pasta integrale cotta in anticipo",role:"base",portions:5,protein:10,prepMin:5,cookMin:12,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["400 g|pasta integrale|Dispensa"]),steps:["Cuoci la pasta 2 minuti meno del tempo in confezione.","Scolala, condiscila con un filo d'olio e stendila su un vassoio.","In frigo entro un'ora, divisa in 5 porzioni da 80 g.","Per scaldarla: in padella con il sugo e un cucchiaio d'acqua, o al microonde coperta."],
 cons:"Frigo 4 giorni. Freezer 2 mesi se al dente.",par:"Bolle da sola: usa l'acqua già calda di un altro cereale se puoi.",think:"La pasta raffreddata e riscaldata ha più amido resistente di quella appena cotta: la retrogradazione dell'amido.",
 draw:{vessel:"plate",pieces:[{t:"penne",c:"#C9A15E",n:28,s:.12}]}},
{id:"pane",name:"Pane integrale",role:"base",portions:5,protein:5,prepMin:0,cookMin:0,equip:"nessuno",fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["300 g|pane integrale|Panetteria"]),steps:["Taglialo a fette appena comprato.","Tieni fuori le fette per 2–3 giorni, il resto in freezer.","Le fette congelate si tostano direttamente."],
 cons:"Dispensa 3 giorni, freezer a fette 3 mesi.",par:"",think:"",
 draw:{vessel:"plate",pieces:[{t:"cube",c:"#B07A43",n:3,s:.32}]}},

/* ---------- CONTORNI ---------- */
{id:"verd_aut",name:"Verdure d'autunno al forno",role:"side",portions:4,protein:4,prepMin:15,cookMin:40,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("9-12"),
 ing:I(["1 kg|zucca|Ortofrutta","1|cavolfiore|Ortofrutta","3|carote|Ortofrutta","2|cipolla rossa|Ortofrutta","3 cucchiai|olio EVO|Basi","2 rametti|rosmarino|Basi"]),
 steps:["Zucca a cubi di 2 cm, cavolfiore a cimette, carote a rondelle, cipolle a spicchi.","Condisci in una ciotola con olio, rosmarino, sale e paprika dolce.","Due teglie, un solo strato. 200 °C per 35–40 minuti, scambiando le teglie a metà."],
 cons:"Frigo 4 giorni. In freezer diventano molli.",par:"Prima cosa in forno.",think:"Verdure ammassate cuociono al vapore: la doratura (Maillard) vuole superficie asciutta e oltre 140 °C.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#E48A2A",n:20,s:.16},{t:"floret",c:"#EFE6CF",n:9,s:.15},{t:"round",c:"#E07A2B",inner:"#F0A35A",n:9,s:.1},{t:"ring",c:"#8E3B6A",n:8,s:.13}]}},
{id:"verd_inv",name:"Broccoli, finocchi e carote al forno",role:"side",portions:4,protein:5,prepMin:15,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("11-3"),
 ing:I(["600 g|broccoli|Ortofrutta","2|finocchi|Ortofrutta","3|carote|Ortofrutta","3 cucchiai|olio EVO|Basi"]),
 steps:["Broccoli a cimette, finocchi a spicchi, carote a bastoncini.","Olio, sale e origano.","200 °C per 30–35 minuti su due teglie."],
 cons:"Frigo 4 giorni.",par:"Prima cosa in forno.",think:"I broccoli contengono glucosinolati: la cottura breve al forno ne salva più della bollitura lunga.",
 draw:{vessel:"tray",pieces:[{t:"floret",c:"#3F7A35",n:14,s:.15},{t:"leafy",c:"#E9EFD8",n:8,s:.16},{t:"round",c:"#E07A2B",inner:"#F0A35A",n:10,s:.09}]}},
{id:"verd_est",name:"Verdure estive al forno",role:"side",portions:4,protein:3,prepMin:15,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["2|zucchine|Ortofrutta","2|peperoni|Ortofrutta","1|melanzana|Ortofrutta","1|cipolla rossa|Ortofrutta","3 cucchiai|olio EVO|Basi"]),
 steps:["Tutto a pezzi di 2–3 cm.","Olio, sale, origano.","200 °C per 30–35 minuti su due teglie."],
 cons:"Frigo 4 giorni.",par:"Prima cosa in forno.",think:"Le melanzane assorbono olio come spugne: condiscile per ultime, con meno olio del previsto.",
 draw:{vessel:"tray",pieces:[{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:12,s:.11},{t:"cube",c:"#D8402B",n:10,s:.14},{t:"cube",c:"#E8C33A",n:8,s:.14},{t:"cube",c:"#4A2C4F",n:8,s:.13}]}},
{id:"piselli",name:"Piselli e carote al cipollotto",role:"side",portions:4,protein:6,prepMin:10,cookMin:15,equip:"fuochi",fridgeDays:4,freezer:true,months:M("3-6"),
 ing:I(["450 g|piselli surgelati|Surgelati","2|carote|Ortofrutta","1 mazzo|cipollotti|Ortofrutta"]),
 steps:["Cipollotti a rondelle nell'olio, 3 minuti.","Carote a dadini e piselli, un bicchiere d'acqua, sale.","15 minuti col coperchio."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Fuoco libero, cuoce da solo.",think:"I piselli sono legumi: danno più proteine di qualsiasi altra verdura.",
 draw:{vessel:"plate",pieces:[{t:"dot",c:"#6FA84A",n:60,s:.03},{t:"cube",c:"#E07A2B",n:14,s:.06}]}},
{id:"slaw",name:"Insalata di cavolo cappuccio e carote",role:"side",portions:5,protein:2,prepMin:15,cookMin:0,equip:"nessuno",fridgeDays:5,freezer:false,months:M("10-4"),
 ing:I(["½|cavolo cappuccio|Ortofrutta","2|carote|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Affetta il cavolo sottilissimo, grattugia le carote.","Condisci con limone, olio e sale: il cavolo regge il condimento per giorni."],
 cons:"Frigo 5 giorni, anche già condita.",par:"Si fa a mano mentre tutto cuoce.",think:"Perché il cavolo condito regge 5 giorni e la lattuga no? Pensa allo spessore delle pareti cellulari.",
 draw:{vessel:"plate",pieces:[{t:"needle",c:"#E9EFD8",n:50,s:.12},{t:"needle",c:"#E8872E",n:30,s:.1}]}},
{id:"spinaci",name:"Spinaci ripassati all'aglio",role:"side",portions:4,protein:4,prepMin:10,cookMin:10,equip:"fuochi",fridgeDays:3,freezer:true,months:M("10-5"),
 ing:I(["800 g|spinaci freschi|Ortofrutta","2 spicchi|aglio|Ortofrutta"]),
 steps:["Lava gli spinaci e cuocili in padella solo con l'acqua rimasta sulle foglie, 3 minuti.","Strizza, poi ripassa con olio e aglio 5 minuti."],
 cons:"Frigo 3 giorni, freezer 3 mesi.",par:"Veloce, mentre sobbolle un'altra pentola.",think:"Il ferro degli spinaci si assorbe meglio con vitamina C: una spruzzata di limone quando mangi.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#2F5E28",n:30,s:.14}]}},
{id:"fagiolini",name:"Fagiolini al limone",role:"side",portions:4,protein:2,prepMin:10,cookMin:10,equip:"fuochi",fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["600 g|fagiolini|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Spunta i fagiolini.","Lessali 8–10 minuti in acqua salata, scolali e passali sotto acqua fredda.","Condisci con olio, limone e sale."],
 cons:"Frigo 4 giorni.",par:"Veloce, sul fuoco libero.",think:"L'acqua fredda ferma la cottura e fissa il verde: la clorofilla si degrada col calore prolungato.",
 draw:{vessel:"plate",pieces:[{t:"needle",c:"#4F8A3A",n:40,s:.2}]}},
{id:"insalata",name:"Insalata lavata per la settimana",role:"side",portions:4,protein:1,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["1 cespo|lattuga|Ortofrutta"]),steps:["Lava le foglie, asciugale benissimo (centrifuga o canovaccio).","Contenitore con un foglio di carta da cucina sul fondo.","Condisci solo quando mangi."],
 cons:"Frigo 4 giorni se ben asciutta.",par:"Si fa a mano mentre tutto cuoce.",think:"L'acqua rimasta sulle foglie è il nemico: favorisce muffe e foglie molli.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#7DB257",n:26,s:.16}]}},
{id:"cetrioli",name:"Cetrioli e cipolla rossa in agrodolce",role:"side",portions:4,protein:1,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["2|cetrioli|Ortofrutta","1|cipolla rossa|Ortofrutta","3 cucchiai|aceto di mele|Basi"]),
 steps:["Cetrioli a rondelle sottili, cipolla a fettine.","Aceto, un cucchiaino di zucchero, sale, un filo d'olio.","Riposo in frigo: migliora dal giorno dopo."],
 cons:"Frigo 4 giorni.",par:"Zero fuochi.",think:"L'acido abbassa il pH e rallenta i batteri: il principio delle conserve sott'aceto, in piccolo.",
 draw:{vessel:"plate",pieces:[{t:"round",c:"#4F8A3A",inner:"#DDE9C2",n:18,s:.13},{t:"ring",c:"#8E3B6A",n:8,s:.1}]}},

/* ---------- PRINCIPALI ---------- */
{id:"merluzzo",name:"Merluzzo gratinato al limone",role:"main",portions:2,protein:34,prepMin:10,cookMin:15,equip:"forno",temp:200,fridgeDays:2,freezer:false,months:M("all"),
 ing:I(["400 g|filetti di merluzzo surgelati|Pesce","4 cucchiai|pangrattato|Dispensa","½|limone|Ortofrutta","1 ciuffo|prezzemolo|Ortofrutta","1 spicchio|aglio|Ortofrutta"]),
 steps:["Scongela i filetti in un sacchetto chiuso a bagno in acqua fredda, 30–40 minuti.","Asciugali bene.","Panatura: pangrattato, prezzemolo, aglio, scorza di limone, olio.","200 °C per 12–15 minuti, finché si sfalda."],
 cons:"Frigo 2 giorni. Non congelare di nuovo.",par:"In forno insieme ad altro a 200 °C.",think:"Perché il pesce cotto ha la finestra più breve? Risposta nella Guida frigo.",
 draw:{vessel:"plate",pieces:[{t:"fillet",c:"#F1EAD8",crumb:"#C98F3E",n:2,s:.5},{t:"wedge",c:"#F2D34A",n:1,s:.2}]}},
{id:"merluzzo_piselli",name:"Merluzzo in umido con piselli",role:"main",portions:3,protein:30,prepMin:10,cookMin:20,equip:"fuochi",fridgeDays:2,freezer:false,months:M("all"),
 ing:I(["450 g|filetti di merluzzo surgelati|Pesce","300 g|piselli surgelati|Surgelati","400 g|pelati|Dispensa","1|cipolla|Ortofrutta"]),
 steps:["Cipolla tritata nell'olio, 5 minuti.","Pelati e piselli, 10 minuti.","Adagia il merluzzo a pezzi (anche ancora semi-congelato), coperchio, 8–10 minuti."],
 cons:"Frigo 2 giorni.",par:"Un fuoco, cuoce da solo.",think:"Il sugo protegge il pesce dal seccarsi quando lo riscaldi.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#C4452C",base2:"#B03A24",pieces:[{t:"flake",c:"#F1EAD8",n:8,s:.2},{t:"dot",c:"#6FA84A",n:40,s:.028}]}},
{id:"polp_merluzzo",name:"Polpette di merluzzo e patate",role:"main",portions:4,protein:23,prepMin:20,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["400 g|filetti di merluzzo surgelati|Pesce","300 g|patate|Ortofrutta","1|uova|Frigo","10 g|lievito alimentare in scaglie|Dispensa","60 g|pangrattato|Dispensa","1 ciuffo|prezzemolo|Ortofrutta"]),
 steps:["Lessa le patate a pezzi (15 min) e schiacciale.","Cuoci il merluzzo 5 minuti in acqua bollente, sbriciolalo.","Unisci tutto con uovo, lievito alimentare, prezzemolo e metà pangrattato.","Forma 20 polpette, passale nel pangrattato. 200 °C per 20 minuti."],
 cons:"Frigo 3 giorni. Freezer: prima sul vassoio, poi in sacchetto.",par:"Le patate lessano mentre il forno lavora.",think:"Pesce scongelato crudo non si ricongela; una volta cotto sì, perché la cottura abbatte la carica batterica.",
 draw:{vessel:"plate",pieces:[{t:"ball",c:"#D9A865",n:9,s:.13},{t:"wedge",c:"#F2D34A",n:1,s:.18}]}},
{id:"polp_tonno",name:"Polpette di tonno e ceci al forno",role:"main",portions:4,protein:25,prepMin:15,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["2 lattine|ceci|Dispensa","3 scatolette|tonno al naturale|Pesce","1|uova|Frigo","15 g|lievito alimentare in scaglie|Dispensa","80 g|pangrattato|Dispensa","½|limone|Ortofrutta"]),
 steps:["Schiaccia i ceci sciacquati con una forchetta.","Unisci tonno, uovo, lievito alimentare, 50 g di pangrattato, scorza di limone, sale.","24 palline passate nel pangrattato rimasto.","200 °C per 20 minuti, girandole a metà."],
 cons:"Frigo 3 giorni. Freezer: prima sul vassoio 2 ore, poi in sacchetto.",par:"L'impasto si fa a mano mentre altro cuoce.",think:"Il tonno è un grande predatore e accumula più mercurio dello sgombro: meglio non tutti i giorni.",
 draw:{vessel:"plate",pieces:[{t:"ball",c:"#C98B45",n:9,s:.13},{t:"leafy",c:"#6FA84A",n:8,s:.12}]}},
{id:"dahl",name:"Dahl di lenticchie rosse e spinaci",role:"main",portions:5,protein:21,prepMin:10,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["400 g|lenticchie rosse decorticate|Dispensa","1|cipolla|Ortofrutta","400 g|pelati|Dispensa","200 ml|latte di cocco|Dispensa","200 g|spinaci surgelati|Surgelati","1 cucchiaino|curcuma|Basi"]),
 steps:["Cipolla e aglio nell'olio, 5 minuti.","Curcuma e cumino, un minuto. (Niente peperoncino: il sapore viene dalle spezie dolci.)","Lenticchie, pelati e 1,1 litri d'acqua: 25 minuti a fuoco basso.","Ultimi 5 minuti: spinaci e latte di cocco. Sala alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi. Si addensa: allunga con acqua.",par:"Sobbolle da solo.",think:"Il latte di cocco non è un latticino: è l'emulsione della polpa di cocco con acqua.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#E1A133",base2:"#D48F24",pieces:[{t:"swirl",c:"#F6EBD8",n:2,s:.5},{t:"leafy",c:"#3B6E2E",n:10,s:.11}]}},
{id:"stufato",name:"Stufato di fagioli e lenticchie",role:"main",portions:4,protein:22,prepMin:10,cookMin:40,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["2 lattine|fagioli borlotti|Dispensa","200 g|lenticchie secche|Dispensa","800 g|pelati|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 cucchiaino|paprika dolce|Basi"]),
 steps:["Cipolla e carota tritate nell'olio, 5 minuti.","Paprika dolce e un pizzico di cumino, un minuto.","Lenticchie, pelati e 500 ml d'acqua: 30 minuti.","Aggiungi i borlotti sciacquati, altri 10 minuti. Sala."],
 cons:"Frigo 4 giorni, freezer 3 mesi: migliora il giorno dopo.",par:"Sobbolle da solo, mescola ogni tanto.",think:"Legumi e cereali nello stesso giorno coprono tutti gli aminoacidi essenziali: la lisina dei legumi compensa quella che manca ai cereali.",
 draw:{vessel:"bowl",bowl:"#3A2E28",base:"#9E3A22",base2:"#8A2F1A",pieces:[{t:"flake",c:"#6B2F25",n:30,s:.06},{t:"dot",c:"#E8C33A",n:8,s:.02}]}},
{id:"lenticchie",name:"Lenticchie in umido",role:"main",portions:4,protein:19,prepMin:10,cookMin:35,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["300 g|lenticchie secche|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 costa|sedano|Ortofrutta","2 cucchiai|concentrato di pomodoro|Dispensa"]),
 steps:["Soffritto di cipolla, carota e sedano, 5 minuti.","Concentrato, lenticchie sciacquate, acqua a coprire di 3 dita.","35 minuti a fuoco basso, sala alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da solo.",think:"Perché salare alla fine? Il sale all'inizio può rallentare l'ammorbidimento della buccia di alcuni legumi.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#7A5A3A",base2:"#6B4C30",pieces:[{t:"grain",c:"#8B6A45",n:120,s:.03},{t:"cube",c:"#E07A2B",n:8,s:.05}]}},
{id:"cannellini_tonno",name:"Cannellini, tonno e cipolla rossa",role:"main",portions:3,protein:25,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:3,freezer:false,months:M("all"),
 ing:I(["2 lattine|fagioli cannellini|Dispensa","3 scatolette|tonno al naturale|Pesce","1|cipolla rossa|Ortofrutta","1 ciuffo|prezzemolo|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Cipolla a fettine sottili, 10 minuti in acqua e aceto per addolcirla.","Unisci cannellini sciacquati, tonno, prezzemolo, limone, olio e sale."],
 cons:"Frigo 3 giorni. Non si congela.",par:"Zero fuochi: si fa mentre tutto cuoce.",think:"Perché mettere la cipolla in acqua e aceto? L'acido neutralizza parte dei composti solforati pungenti.",
 draw:{vessel:"plate",pieces:[{t:"leaf",c:"#F3EEDD",n:40,s:.08},{t:"flake",c:"#C9B59A",n:8,s:.1},{t:"ring",c:"#8E3B6A",n:6,s:.1}]}},
{id:"frit_zucchine",name:"Frittata al forno con zucchine e tofu",role:"main",portions:3,protein:26,prepMin:10,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("5-10"),
 ing:I(["8|uova|Frigo","150 g|tofu naturale|Frigo","10 g|lievito alimentare in scaglie|Dispensa","2|zucchine|Ortofrutta"]),
 steps:["Frulla il tofu con due uova fino a una crema (o schiaccialo bene con la forchetta).","Sbatti con le altre uova, lievito alimentare, sale e pepe.","Teglia da 22 cm con carta forno unta, zucchine a rondelle sottili, uova sopra.","180 °C per 25 minuti, finché il centro non trema."],
 cons:"Frigo 4 giorni. In freezer diventa acquosa.",par:"Di solito ultimo giro di forno, a 180 °C.",think:"Il tofu frullato fa la parte della ricotta: morbidezza e proteine, senza latticini.",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:14,s:.09}]}},
{id:"frit_broccoli",name:"Frittata al forno con broccoli e tofu",role:"main",portions:3,protein:27,prepMin:15,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("10-4"),
 ing:I(["8|uova|Frigo","150 g|tofu naturale|Frigo","10 g|lievito alimentare in scaglie|Dispensa","300 g|broccoli|Ortofrutta"]),
 steps:["Cimette di broccoli sbollentate 3 minuti.","Frulla il tofu con due uova, poi sbatti con le altre, lievito alimentare, sale.","Teglia da 22 cm unta: broccoli e uova. 180 °C per 25 minuti."],
 cons:"Frigo 4 giorni.",par:"Sbollenta i broccoli nell'acqua che bolle per il cereale.",think:"",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"floret",c:"#3F7A35",n:10,s:.12}]}},
{id:"frit_asparagi",name:"Frittata al forno con asparagi e tofu",role:"main",portions:3,protein:28,prepMin:10,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("4-5"),
 ing:I(["8|uova|Frigo","150 g|tofu naturale|Frigo","10 g|lievito alimentare in scaglie|Dispensa","400 g|asparagi|Ortofrutta"]),
 steps:["Togli la parte legnosa degli asparagi, tagliali a tocchetti.","Frulla il tofu con due uova, poi sbatti con le altre, lievito alimentare, sale.","Teglia unta, asparagi, uova. 180 °C per 25 minuti."],
 cons:"Frigo 4 giorni.",par:"Ultimo giro di forno.",think:"",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"needle",c:"#4F8A3A",n:14,s:.22}]}},
{id:"torta_spinaci",name:"Torta salata di tofu e spinaci",role:"main",portions:4,protein:23,prepMin:15,cookMin:40,equip:"forno",temp:180,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["1 rotolo|pasta brisé|Frigo","300 g|tofu naturale|Frigo","3|uova|Frigo","450 g|spinaci surgelati|Surgelati","15 g|lievito alimentare in scaglie|Dispensa"]),
 steps:["Spinaci scongelati e strizzati benissimo.","Frulla il tofu con le uova, unisci spinaci, lievito alimentare, sale e noce moscata.","Stendi la brisé nella teglia, bucherella, versa il ripieno.","180 °C per 40 minuti."],
 cons:"Frigo 3 giorni, freezer a fette 2 mesi.",par:"Lunga in forno: mettila presto.",think:"Molte brisé del supermercato sono già fatte con grassi vegetali: guarda l'etichetta.",
 draw:{vessel:"pan",base:"#D9A865",base2:"#2F5E28",slices:6,pieces:[{t:"leafy",c:"#2F5E28",n:20,s:.1}]}},
{id:"tofu",name:"Tofu al forno con soia e sesamo",role:"main",portions:3,protein:19,prepMin:10,cookMin:25,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["400 g|tofu naturale|Frigo","3 cucchiai|salsa di soia|Dispensa","1 cucchiaio|semi di sesamo|Dispensa","1 cucchiaio|amido di mais|Dispensa"]),
 steps:["Tampona il tofu con carta, taglialo a cubi.","Condisci con soia e olio, poi spolvera con l'amido.","200 °C per 25 minuti, girando a metà. Sesamo alla fine."],
 cons:"Frigo 4 giorni. In freezer diventa spugnoso.",par:"In forno con altro a 200 °C.",think:"L'amido crea una crosticina asciutta: senza, il tofu rilascia acqua e cuoce al vapore.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#E3C48C",n:26,s:.14},{t:"dot",c:"#F4EBD2",n:30,s:.012}]}},
{id:"sugo_sgombro",name:"Sugo di sgombro, capperi e olive",role:"main",portions:4,protein:17,prepMin:5,cookMin:20,equip:"fuochi",fridgeDays:3,freezer:true,needsBase:"pasta",months:M("all"),
 ing:I(["3 scatolette|sgombro al naturale|Pesce","700 g|passata di pomodoro|Dispensa","1|cipolla|Ortofrutta","1 cucchiaio|capperi|Dispensa","10|olive nere|Dispensa"]),
 steps:["Cipolla e aglio nell'olio, 5 minuti.","Passata, sale e origano: 15 minuti.","Capperi, olive e sgombro a pezzi: altri 5 minuti."],
 cons:"Frigo 3 giorni, freezer 3 mesi.",par:"Un fuoco, cuoce da solo.",think:"Lo sgombro è piccolo e ricco di omega-3, e costa molto meno del salmone.",
 draw:{vessel:"plate",pastaBed:"#B53A24",pieces:[{t:"penne",c:"#E9C27A",n:24,s:.12},{t:"flake",c:"#C9B59A",n:7,s:.09},{t:"olive",c:"#2A2322",n:6,s:.05}]}},
{id:"sardine",name:"Sardine gratinate al forno",role:"main",portions:3,protein:28,prepMin:20,cookMin:15,equip:"forno",temp:200,fridgeDays:2,freezer:false,months:M("4-9"),
 ing:I(["700 g|sardine fresche|Pesce","4 cucchiai|pangrattato|Dispensa","1 ciuffo|prezzemolo|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Pulisci le sardine: testa via, apri a libro, togli la lisca (o chiedilo al banco).","Disponile in teglia, pelle sotto.","Pangrattato, prezzemolo, aglio, scorza di limone, olio. 200 °C per 12–15 minuti."],
 cons:"Frigo 2 giorni.",par:"In forno con altro a 200 °C.",think:"Pesce azzurro di stagione: costa poco perché se ne pesca tanto, e ha pochissimo mercurio.",
 draw:{vessel:"tray",pieces:[{t:"fillet",c:"#9FB3BF",crumb:"#C98F3E",n:2,s:.45}]}},
{id:"peperoni_ripieni",name:"Peperoni ripieni di tonno e riso",role:"main",portions:3,protein:21,prepMin:20,cookMin:40,equip:"forno",temp:180,fridgeDays:3,freezer:true,months:M("7-9"),
 ing:I(["3|peperoni|Ortofrutta","150 g|riso|Dispensa","3 scatolette|tonno al naturale|Pesce","1|uova|Frigo","10 g|lievito alimentare in scaglie|Dispensa","200 g|passata di pomodoro|Dispensa"]),
 steps:["Lessa il riso 10 minuti (resta indietro di cottura).","Mescola riso, tonno, uovo, lievito alimentare, un po' di passata.","Riempi i peperoni tagliati a metà, passata sul fondo della teglia.","180 °C per 40 minuti."],
 cons:"Frigo 3 giorni, freezer 2 mesi.",par:"Il riso lessa mentre pulisci i peperoni.",think:"",
 draw:{vessel:"tray",pieces:[{t:"leafy",c:"#D8402B",n:6,s:.3},{t:"dot",c:"#F2E3C0",n:40,s:.02}]}},
{id:"parmigiana",name:"Parmigiana di melanzane leggera",role:"main",portions:4,protein:18,prepMin:25,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:true,dairy:true,months:M("7-9"),
 ing:I(["2|melanzana|Ortofrutta","500 g|passata di pomodoro|Dispensa","250 g|mozzarella|Frigo","50 g|parmigiano grattugiato|Frigo","1 vasetto|basilico|Ortofrutta"]),
 steps:["Melanzane a fette, spennellate d'olio, 200 °C per 15 minuti (invece di friggerle).","Strati: passata, melanzane, mozzarella a dadini, parmigiano, basilico.","200 °C per 20 minuti."],
 cons:"Frigo 4 giorni, freezer 3 mesi: migliora riposando.",par:"Le melanzane vanno in forno mentre prepari il resto.",think:"Qui i latticini animali restano: le mozzarelle vegetali hanno pochissime proteine e non filano allo stesso modo.",
 draw:{vessel:"tray",pieces:[{t:"leafy",c:"#B53A24",n:14,s:.25},{t:"dot",c:"#F4EFE2",n:30,s:.04},{t:"leaf",c:"#3F7D34",n:6,s:.07}]}},
{id:"zuppa_ceci",name:"Zuppa di ceci e cavolo nero",role:"main",portions:4,protein:17,prepMin:15,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("11-3"),
 ing:I(["3 lattine|ceci|Dispensa","300 g|cavolo nero|Ortofrutta","1|cipolla|Ortofrutta","1|carote|Ortofrutta","10 g|lievito alimentare in scaglie|Dispensa"]),
 steps:["Soffritto di cipolla e carota.","Cavolo nero a striscioline senza costa centrale, 5 minuti.","Ceci e 1 litro d'acqua, 25 minuti. Frulla un terzo per renderla cremosa.","Lievito alimentare al momento di servire."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da sola.",think:"Il cavolo nero migliora dopo la prima gelata: il freddo trasforma parte dell'amido in zuccheri.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#D9B97A",base2:"#C9A565",pieces:[{t:"leafy",c:"#243F22",n:14,s:.12},{t:"dot",c:"#E3C893",n:30,s:.035}]}},
{id:"vellutata_zucca",name:"Vellutata di zucca e lenticchie rosse",role:"main",portions:4,protein:17,prepMin:15,cookMin:25,equip:"fuochi",fridgeDays:4,freezer:true,months:M("9-1"),
 ing:I(["800 g|zucca|Ortofrutta","250 g|lenticchie rosse decorticate|Dispensa","1|cipolla|Ortofrutta","1 rametto|rosmarino|Basi"]),
 steps:["Cipolla e rosmarino nell'olio.","Zucca a cubi, lenticchie e 1,2 litri d'acqua: 25 minuti.","Frulla col minipimer, sala."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da sola.",think:"Le lenticchie rosse, senza buccia, si sciolgono e addensano: la vellutata non ha bisogno di patate.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#E8892E",base2:"#DB7A22",pieces:[{t:"swirl",c:"#F6EBD8",n:1,s:.5},{t:"dot",c:"#3F6B3A",n:12,s:.02}]}},

/* ---------- SCORTE DA FREEZER ---------- */
{id:"s_ragu_lenticchie",name:"Ragù di lenticchie",role:"scorta",portions:8,protein:10,prepMin:15,cookMin:45,equip:"fuochi",freezerMonths:3,months:M("all"),uses:"pasta, riso, polenta, patate al forno",
 ing:I(["300 g|lenticchie secche|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 costa|sedano|Ortofrutta","700 g|passata di pomodoro|Dispensa"]),
 steps:["Trita finissimi cipolla, carota e sedano; soffriggi 8 minuti.","Lenticchie sciacquate, passata e 600 ml d'acqua.","45 minuti a fuoco basso, finché è denso come un ragù.","Dividi in 8 porzioni (circa 150 g) in sacchetti stesi piatti."],
 cons:"Freezer 3 mesi. Dopo lo scongelamento, frigo 3 giorni.",par:"Sobbolle a lungo da solo.",think:"Perché congelare in sacchetti piatti? Più superficie: congela e scongela molto più in fretta."},
{id:"s_sugo_tonno",name:"Sugo di tonno, capperi e olive",role:"scorta",portions:6,protein:15,prepMin:5,cookMin:20,equip:"fuochi",freezerMonths:3,months:M("all"),uses:"pasta, riso, orzo",
 ing:I(["6 scatolette|tonno al naturale|Pesce","700 g|passata di pomodoro|Dispensa","1|cipolla|Ortofrutta","1 cucchiaio|capperi|Dispensa","10|olive nere|Dispensa"]),
 steps:["Cipolla nell'olio, 5 minuti.","Passata e origano, 15 minuti.","Tonno, capperi e olive: 3 minuti. Dividi in 6 porzioni."],
 cons:"Freezer 3 mesi. Scongelato, frigo 2 giorni.",par:"Un fuoco.",think:""},
{id:"s_pomodoro",name:"Sugo di pomodori freschi e basilico",role:"scorta",portions:8,protein:2,prepMin:20,cookMin:40,equip:"fuochi",freezerMonths:6,months:M("7-9"),uses:"pasta, riso, legumi, uova in camicia, base per altri sughi",
 ing:I(["2 kg|pomodori maturi|Ortofrutta","1|cipolla|Ortofrutta","1 vasetto|basilico|Ortofrutta"]),
 steps:["Incidi a croce i pomodori, 1 minuto in acqua bollente, pelali e tagliali.","Cipolla nell'olio, poi i pomodori: 40 minuti a fuoco basso.","Basilico alla fine. Porzioni in vasetti o sacchetti."],
 cons:"Freezer 6 mesi.",par:"Sobbolle da solo.",think:"Ad agosto i pomodori costano meno e sanno di più: la scorta \"congela\" anche il prezzo."},
{id:"s_pesto_basilico",name:"Pesto di basilico e semi di girasole",role:"scorta",portions:10,protein:2,prepMin:15,cookMin:0,equip:"nessuno",freezerMonths:6,months:M("6-9"),uses:"pasta, riso, legumi, patate, in un minestrone",
 ing:I(["2 vasetti|basilico|Ortofrutta","60 g|semi di girasole|Dispensa","20 g|lievito alimentare in scaglie|Dispensa","1 spicchio|aglio|Ortofrutta","120 ml|olio EVO|Basi"]),
 steps:["Frulla basilico, semi, lievito alimentare, aglio e sale con l'olio a filo.","Riempi uno stampo per cubetti di ghiaccio, copri con un velo d'olio.","Una volta congelati, passa i cubetti in un sacchetto."],
 cons:"Freezer 6 mesi a cubetti. Un cubetto = una porzione.",par:"Zero fuochi.",think:"Il velo d'olio impedisce all'aria di toccare il basilico: niente ossidazione, niente pesto nero."},
{id:"s_pesto_cavolo",name:"Pesto di cavolo nero e noci",role:"scorta",portions:10,protein:3,prepMin:15,cookMin:5,equip:"fuochi",freezerMonths:6,months:M("11-3"),uses:"pasta, orzo, farro, bruschette, zuppe",
 ing:I(["300 g|cavolo nero|Ortofrutta","50 g|noci|Dispensa","20 g|lievito alimentare in scaglie|Dispensa","1 spicchio|aglio|Ortofrutta","100 ml|olio EVO|Basi"]),
 steps:["Togli la costa al cavolo nero, sbollentalo 4 minuti, strizzalo.","Frulla con noci, lievito alimentare, aglio, sale e l'olio a filo.","Cubetti in freezer come il pesto di basilico."],
 cons:"Freezer 6 mesi a cubetti.",par:"Sbollenta nell'acqua già calda di un cereale.",think:""},
{id:"s_pesto_rucola",name:"Pesto di rucola e mandorle",role:"scorta",portions:10,protein:2,prepMin:10,cookMin:0,equip:"nessuno",freezerMonths:6,months:[4,5,6,9,10],uses:"pasta, riso, cereali, legumi",
 ing:I(["100 g|rucola|Ortofrutta","50 g|mandorle|Dispensa","20 g|lievito alimentare in scaglie|Dispensa","100 ml|olio EVO|Basi"]),
 steps:["Frulla rucola, mandorle, lievito alimentare e sale con l'olio a filo.","Cubetti in freezer."],
 cons:"Freezer 6 mesi a cubetti.",par:"Zero fuochi.",think:"La rucola è amara perché contiene glucosinolati, gli stessi composti di cavoli e broccoli."},
{id:"s_crema_zucca",name:"Crema di zucca e ceci",role:"scorta",portions:8,protein:5,prepMin:15,cookMin:25,equip:"fuochi",freezerMonths:3,months:M("9-12"),uses:"pasta, riso, orzo, come vellutata allungata",
 ing:I(["1 kg|zucca|Ortofrutta","2 lattine|ceci|Dispensa","1|cipolla|Ortofrutta","1 rametto|rosmarino|Basi"]),
 steps:["Cipolla e rosmarino nell'olio.","Zucca a cubi e un bicchiere d'acqua, 20 minuti col coperchio.","Aggiungi i ceci, 5 minuti, frulla tutto. Porzioni da 150 g."],
 cons:"Freezer 3 mesi.",par:"Un fuoco.",think:""},
{id:"s_crema_piselli",name:"Crema di piselli e menta",role:"scorta",portions:8,protein:6,prepMin:10,cookMin:15,equip:"fuochi",freezerMonths:3,months:M("3-6"),uses:"pasta, riso, crostini, con uova sode",
 ing:I(["900 g|piselli surgelati|Surgelati","1 mazzo|cipollotti|Ortofrutta","1 mazzetto|menta|Ortofrutta"]),
 steps:["Cipollotti nell'olio, 3 minuti.","Piselli e un bicchiere d'acqua, 12 minuti.","Frulla con la menta e un filo d'olio. Porzioni da 150 g."],
 cons:"Freezer 3 mesi.",par:"Un fuoco.",think:""},
{id:"s_peperoni",name:"Sugo di peperoni dolci",role:"scorta",portions:8,protein:2,prepMin:15,cookMin:35,equip:"fuochi",freezerMonths:6,months:M("7-9"),uses:"pasta, riso, legumi, uova",
 ing:I(["1 kg|peperoni|Ortofrutta","400 g|pelati|Dispensa","1|cipolla|Ortofrutta"]),
 steps:["Peperoni a listarelle, cipolla a fettine.","Stufa in padella con olio, coperchio, 20 minuti.","Pelati, altri 15 minuti. Frulla metà per renderlo cremoso."],
 cons:"Freezer 6 mesi.",par:"Un fuoco.",think:"Peperoni dolci, niente peperoncino: il colore rosso viene dai carotenoidi, non dalla capsaicina."},

/* ---------- DOLCI ---------- */
{id:"d_barrette",name:"Barrette di granola",role:"dolce",portions:10,protein:6,prepMin:15,cookMin:20,equip:"forno",temp:170,store:{dispensa:7,frigo:14,freezer:3},months:M("all"),
 ing:I(["200 g|fiocchi d'avena|Dispensa","100 g|burro di arachidi|Dispensa","80 g|miele|Dispensa","60 g|semi di girasole|Dispensa","50 g|uvetta|Dispensa","40 g|gocce di cioccolato fondente|Dispensa"]),
 steps:["Scalda burro di arachidi e miele 1 minuto, mescola.","Unisci avena, semi, uvetta e un pizzico di sale. Ultime le gocce di cioccolato.","Pressa forte in una teglia 20×20 con carta forno.","170 °C per 20 minuti. Taglia in 10 solo quando è completamente fredda."],
 cons:"Dispensa 1 settimana in scatola ermetica, frigo 2 settimane, freezer 3 mesi.",par:"In forno quando è a 170–180 °C, insieme ad altro.",think:"Perché tagliarle solo da fredde? Il miele caldo è fluido; raffreddandosi fa da colla."},
{id:"d_granola",name:"Granola croccante in barattolo",role:"dolce",portions:10,protein:7,prepMin:10,cookMin:25,equip:"forno",temp:160,store:{dispensa:30,frigo:0,freezer:0},months:M("all"),
 ing:I(["300 g|fiocchi d'avena|Dispensa","80 g|mandorle|Dispensa","60 g|semi di zucca|Dispensa","80 g|miele|Dispensa","50 ml|olio di semi|Dispensa"]),
 steps:["Mescola avena, mandorle tritate grossolanamente, semi, cannella e sale.","Aggiungi miele e olio, mescola bene.","Stendi su teglia, 160 °C per 25 minuti mescolando a metà.","Diventa croccante raffreddandosi: poi in barattolo."],
 cons:"Dispensa 1 mese in barattolo chiuso.",par:"Forno a 160 °C: meglio come ultimo giro.",think:"Con yogurt di soia e frutta diventa una colazione da 15 g di proteine."},
{id:"d_energy",name:"Palline di datteri e cacao",role:"dolce",portions:16,protein:2,prepMin:15,cookMin:0,equip:"nessuno",store:{dispensa:2,frigo:10,freezer:3},months:M("all"),
 ing:I(["200 g|datteri|Dispensa","100 g|fiocchi d'avena|Dispensa","60 g|burro di arachidi|Dispensa","20 g|cacao amaro|Dispensa"]),
 steps:["Ammolla i datteri snocciolati 10 minuti in acqua calda, scolali.","Schiacciali con la forchetta (o minipimer) con burro di arachidi e cacao.","Unisci l'avena, forma 16 palline."],
 cons:"Frigo 10 giorni, freezer 3 mesi: si mangiano anche appena tolte.",par:"Zero fuochi.",think:""},
{id:"d_banana",name:"Banana bread all'olio",role:"dolce",portions:10,protein:4,prepMin:15,cookMin:45,equip:"forno",temp:180,store:{dispensa:3,frigo:6,freezer:3},months:M("all"),
 ing:I(["3|banane|Ortofrutta","220 g|farina integrale|Dispensa","60 ml|olio di semi|Dispensa","60 g|zucchero di canna|Dispensa","120 ml|bevanda di soia|Frigo","1 bustina|lievito per dolci|Dispensa","50 g|noci|Dispensa"]),
 steps:["Schiaccia le banane molto mature.","Unisci olio, zucchero e bevanda di soia, poi farina, lievito e noci.","Stampo da plumcake con carta forno, 180 °C per 45 minuti (prova stecchino)."],
 cons:"Dispensa 3 giorni, frigo 6, freezer a fette 3 mesi.",par:"Lungo in forno: mettilo presto.",think:"Più la banana è nera, più amido si è trasformato in zucchero: serve meno zucchero aggiunto."},
{id:"d_mele",name:"Torta di mele all'olio",role:"dolce",portions:10,protein:3,prepMin:20,cookMin:40,equip:"forno",temp:180,store:{dispensa:3,frigo:5,freezer:3},months:M("9-3"),
 ing:I(["3|mele|Ortofrutta","220 g|farina integrale|Dispensa","125 g|yogurt di soia|Frigo","70 ml|olio di semi|Dispensa","80 g|zucchero di canna|Dispensa","1 bustina|lievito per dolci|Dispensa","1|limone|Ortofrutta"]),
 steps:["Mescola yogurt, olio, zucchero e scorza di limone.","Farina e lievito setacciati, poi 2 mele a dadini.","Nello stampo, la terza mela a fettine sopra. 180 °C per 40 minuti."],
 cons:"Dispensa 3 giorni coperta, frigo 5, freezer a fette 3 mesi.",par:"In forno a 180 °C con la frittata o dopo.",think:""},
{id:"d_muffin_pere",name:"Muffin pere e cacao",role:"dolce",portions:12,protein:3,prepMin:15,cookMin:22,equip:"forno",temp:180,store:{dispensa:3,frigo:5,freezer:3},months:M("9-2"),
 ing:I(["2|pere|Ortofrutta","200 g|farina integrale|Dispensa","25 g|cacao amaro|Dispensa","70 g|zucchero di canna|Dispensa","60 ml|olio di semi|Dispensa","180 ml|bevanda di soia|Frigo","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Mescola i liquidi con lo zucchero.","Aggiungi farina, cacao e lievito, poi le pere a dadini.","12 pirottini, 180 °C per 22 minuti."],
 cons:"Dispensa 3 giorni, freezer 3 mesi: si scongelano in un'ora.",par:"In forno a 180 °C.",think:""},
{id:"d_biscotti_zucca",name:"Biscotti morbidi di zucca e avena",role:"dolce",portions:20,protein:2,prepMin:15,cookMin:15,equip:"forno",temp:180,store:{dispensa:5,frigo:7,freezer:3},months:M("10-12"),
 ing:I(["200 g|zucca|Ortofrutta","180 g|fiocchi d'avena|Dispensa","100 g|farina integrale|Dispensa","60 g|zucchero di canna|Dispensa","50 ml|olio di semi|Dispensa","½ bustina|lievito per dolci|Dispensa"]),
 steps:["Grattugia la zucca cruda finissima.","Mescola con olio, zucchero, cannella, poi avena, farina e lievito.","20 mucchietti su teglia, 180 °C per 15 minuti."],
 cons:"Dispensa 5 giorni in latta, freezer 3 mesi.",par:"Usa un pezzo della zucca comprata per le verdure.",think:""},
{id:"d_plumcake_arancia",name:"Plumcake all'arancia",role:"dolce",portions:10,protein:3,prepMin:15,cookMin:45,equip:"forno",temp:175,store:{dispensa:3,frigo:5,freezer:3},months:M("12-3"),
 ing:I(["2|arance|Ortofrutta","250 g|farina integrale|Dispensa","125 g|yogurt di soia|Frigo","80 g|zucchero di canna|Dispensa","70 ml|olio di semi|Dispensa","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Scorza e succo delle arance (circa 150 ml).","Mescola succo, scorza, yogurt, olio e zucchero, poi farina e lievito.","Stampo da plumcake, 175 °C per 45 minuti."],
 cons:"Dispensa 3 giorni, frigo 5, freezer a fette 3 mesi.",par:"Lungo in forno.",think:""},
{id:"d_barrette_fragole",name:"Barrette crumble alle fragole",role:"dolce",portions:10,protein:4,prepMin:15,cookMin:30,equip:"forno",temp:180,store:{dispensa:0,frigo:4,freezer:2},months:M("4-6"),
 ing:I(["250 g|fragole|Ortofrutta","200 g|fiocchi d'avena|Dispensa","100 g|farina integrale|Dispensa","70 ml|olio di semi|Dispensa","60 g|zucchero di canna|Dispensa"]),
 steps:["Mescola avena, farina, zucchero, olio e un pizzico di sale: deve sbriciolarsi.","Pressa due terzi in teglia, fragole a pezzi sopra, resto a briciole.","180 °C per 30 minuti. Taglia da fredda."],
 cons:"Frigo 4 giorni (la frutta è umida), freezer 2 mesi.",par:"In forno a 180 °C.",think:""},
{id:"d_muffin_albicocche",name:"Muffin alle albicocche",role:"dolce",portions:12,protein:3,prepMin:15,cookMin:22,equip:"forno",temp:180,store:{dispensa:2,frigo:4,freezer:3},months:M("6-8"),
 ing:I(["4|albicocche|Ortofrutta","220 g|farina integrale|Dispensa","125 g|yogurt di soia|Frigo","70 g|zucchero di canna|Dispensa","60 ml|olio di semi|Dispensa","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Yogurt, olio e zucchero, poi farina e lievito.","Albicocche a dadini.","12 pirottini, 180 °C per 22 minuti."],
 cons:"Dispensa 2 giorni, frigo 4, freezer 3 mesi.",par:"In forno a 180 °C.",think:""},
{id:"d_bark",name:"Tavoletta gelata di yogurt di soia e pesche",role:"dolce",portions:8,protein:3,prepMin:10,cookMin:0,equip:"nessuno",store:{dispensa:0,frigo:0,freezer:2},months:M("6-9"),
 ing:I(["500 g|yogurt di soia|Frigo","2|pesche|Ortofrutta","2 cucchiai|miele|Dispensa","50 g|granola|Dispensa"]),
 steps:["Mescola yogurt e miele, stendi 1 cm su una teglia con carta forno.","Pesche a dadini e granola sopra.","Freezer 3 ore, poi spezzala a pezzi e tienila in un sacchetto."],
 cons:"Solo freezer, 2 mesi. Si mangia 5 minuti dopo averla tolta.",par:"Zero fuochi.",think:"Perché resta morbida e non diventa un blocco di ghiaccio? Zuccheri e proteine abbassano il punto di congelamento."}
].map(r=>({temp:0,needsBase:"",fav:false,photo:null,cons:"",par:"",think:"",dairy:false,spicy:false,fridgeDays:0,freezer:false,...r}));

/* Illustrazioni per scorte e dolci */
const DRAW_EXTRA={
 s_ragu_lenticchie:{vessel:"bowl",bowl:"#3A2E28",base:"#8E3522",base2:"#7A2C1C",pieces:[{t:"grain",c:"#6B3A25",n:90,s:.03},{t:"cube",c:"#E07A2B",n:8,s:.05}]},
 s_sugo_tonno:{vessel:"bowl",bowl:"#26394A",base:"#C4452C",base2:"#B03A24",pieces:[{t:"flake",c:"#D9C4A5",n:14,s:.1},{t:"olive",c:"#2A2322",n:6,s:.045},{t:"dot",c:"#5E7A2E",n:10,s:.02}]},
 s_pomodoro:{vessel:"bowl",bowl:"#2F5F66",base:"#D2412A",base2:"#BF3620",pieces:[{t:"leaf",c:"#3F7D34",n:5,s:.1}]},
 s_pesto_basilico:{vessel:"bowl",bowl:"#5B4A3A",base:"#4F8A2E",base2:"#3F7524",pieces:[{t:"dot",c:"#DCCB86",n:20,s:.018}]},
 s_pesto_cavolo:{vessel:"bowl",bowl:"#5B4A3A",base:"#2F4F2A",base2:"#26421F",pieces:[{t:"flake",c:"#B08A5A",n:10,s:.06}]},
 s_pesto_rucola:{vessel:"bowl",bowl:"#2F5F66",base:"#5C8F3A",base2:"#4C7C2E",pieces:[{t:"flake",c:"#E6D3B0",n:10,s:.05}]},
 s_crema_zucca:{vessel:"bowl",bowl:"#26394A",base:"#E8892E",base2:"#DB7A22",pieces:[{t:"dot",c:"#E3C893",n:14,s:.03},{t:"needle",c:"#3F6B3A",n:5,s:.08}]},
 s_crema_piselli:{vessel:"bowl",bowl:"#5B4A3A",base:"#8DBE55",base2:"#7DAE45",pieces:[{t:"leaf",c:"#2F6B3A",n:5,s:.08},{t:"swirl",c:"#EEF3DE",n:1,s:.4}]},
 s_peperoni:{vessel:"bowl",bowl:"#2F5F66",base:"#D9542E",base2:"#C8461F",pieces:[{t:"needle",c:"#E8C33A",n:10,s:.12}]},
 d_barrette:{vessel:"tray",pieces:[{t:"cube",c:"#C9955A",n:12,s:.28},{t:"dot",c:"#3A2418",n:30,s:.015}]},
 d_granola:{vessel:"bowl",bowl:"#2F5F66",base:"#D2A865",base2:"#C08F4C",pieces:[{t:"flake",c:"#B7843F",n:40,s:.06},{t:"dot",c:"#3F6B3A",n:12,s:.02}]},
 d_energy:{vessel:"plate",pieces:[{t:"ball",c:"#5A3524",n:10,s:.17}]},
 d_banana:{vessel:"tray",pieces:[{t:"cube",c:"#9A6A3A",n:6,s:.32},{t:"dot",c:"#F0D9A0",n:20,s:.02}]},
 d_mele:{vessel:"pan",base:"#D8A55A",base2:"#C9924A",slices:8,pieces:[{t:"leaf",c:"#F3E3A8",n:18,s:.14}]},
 d_muffin_pere:{vessel:"plate",pieces:[{t:"ball",c:"#4A2E22",n:6,s:.26}]},
 d_biscotti_zucca:{vessel:"plate",pieces:[{t:"ball",c:"#D9923E",n:9,s:.18}]},
 d_plumcake_arancia:{vessel:"tray",pieces:[{t:"cube",c:"#E0A64A",n:6,s:.32},{t:"needle",c:"#E8872E",n:10,s:.06}]},
 d_barrette_fragole:{vessel:"tray",pieces:[{t:"cube",c:"#D7B07A",n:12,s:.27},{t:"dot",c:"#C8303A",n:30,s:.025}]},
 d_muffin_albicocche:{vessel:"plate",pieces:[{t:"ball",c:"#E2A24A",n:6,s:.26},{t:"dot",c:"#F08A2A",n:10,s:.03}]},
 d_bark:{vessel:"tray",pieces:[{t:"flake",c:"#F4EFE2",n:14,s:.3},{t:"cube",c:"#F2A65A",n:14,s:.07}]}
};
LIB.forEach(r=>{if(!r.draw&&DRAW_EXTRA[r.id])r.draw=DRAW_EXTRA[r.id]});

/* Aggiunte proteiche (vegetali o uova): l'app le usa quando un giorno resta sotto i 60 g */
const BOOSTERS=[
 {id:"uova",name:"2 uova sode",protein:12,ing:{q:"2",n:"uova",r:"Frigo"},prep:true},
 {id:"edamame",name:"Edamame",protein:11,ing:{q:"100 g",n:"edamame surgelati",r:"Surgelati"}},
 {id:"tofu_aff",name:"Tofu affumicato a cubetti",protein:10,ing:{q:"60 g",n:"tofu affumicato",r:"Frigo"}},
 {id:"yogurt_soia",name:"Salsa di yogurt di soia",protein:6,ing:{q:"150 g",n:"yogurt di soia",r:"Frigo"}},
 {id:"ceci",name:"Ceci",protein:7,ing:{q:"100 g",n:"ceci",r:"Dispensa"}},
 {id:"lievito",name:"Lievito alimentare",protein:5,ing:{q:"10 g",n:"lievito alimentare in scaglie",r:"Dispensa"}}
];
const PROT_MIN=60, PROT_TARGET=62, PROT_MAX=70;
