/* ============ RICETTARIO ============
 role: main (fonte proteica) | base (cereale, porzione 55 g a crudo) | side (contorno)
       scorta (sugo da freezer) | dolce | fermento (verdure fermentate)
 protein, kcal: per porzione (stime da tabelle di composizione, ±10%; l'olio di cottura è incluso,
       quello a crudo aggiunto a tavola no: 1 cucchiaino = 45 kcal)
 family (basi): famiglia botanica del cereale, per variare davvero
 oily: pesce azzurro (omega-3 EPA/DHA) · spicy: piccante (mai proposto)
 store (dolci): giorni in dispensa / giorni in frigo / mesi in freezer
 sugar: zuccheri aggiunti per pezzo (g) */
const LIB_VERSION=7;
const REPARTI=["Ortofrutta","Pesce","Frigo","Surgelati","Dispensa","Panetteria","Basi"];
function M(r){if(Array.isArray(r))return r;if(r==="all")return[1,2,3,4,5,6,7,8,9,10,11,12];const[a,b]=r.split("-").map(Number);const o=[];let m=a;for(;;){o.push(m);if(m===b)break;m=m%12+1}return o}
function I(list){return list.map(s=>{const[q,n,r]=s.split("|");return{q,n,r}})}
const FAMILY_LABEL={legumi:"pasta di legumi",frumento:"frumento",orzo:"orzo",riso:"riso",mais:"mais",saraceno:"grano saraceno",miglio:"miglio",quinoa:"quinoa"};
const LIB=[
/* ---------- BASI: 5 porzioni da 55 g ---------- */
{id:"farro",name:"Farro perlato",role:"base",family:"frumento",portions:5,protein:8,kcal:185,prepMin:5,cookMin:25,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|farro perlato|Dispensa"]),steps:["Sciacqua il farro.","Cuocilo 20–25 minuti in abbondante acqua salata in bollore.","Scolalo al dente, stendilo su un vassoio con un filo d'olio e fallo raffreddare al massimo un'ora.","Dividi in 5 porzioni da circa 140 g cotto (55 g a crudo)."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Bolle da solo: intanto prepari altro.",think:"Il farro è un frumento antico: se in settimana c'è già pasta o couscous, stai mangiando due volte la stessa pianta."},
{id:"orzo",name:"Orzo perlato",role:"base",family:"orzo",portions:5,protein:5,kcal:193,prepMin:5,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|orzo perlato|Dispensa"]),steps:["Sciacqua l'orzo.","Cuocilo 25–30 minuti in acqua salata.","Scola, stendi a raffreddare con un filo d'olio, dividi in 5 porzioni."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Bolle da solo.",think:"Ricco di beta-glucani, le fibre solubili che abbassano un po' il colesterolo LDL."},
{id:"riso",name:"Riso integrale",role:"base",family:"riso",portions:5,protein:4,kcal:198,prepMin:5,cookMin:35,equip:"fuochi",fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["275 g|riso integrale|Dispensa"]),steps:["Cuoci il riso 30–35 minuti in acqua salata.","Scolalo e stendilo subito su un vassoio: in frigo entro un'ora.","Quello che serve dopo il terzo giorno va in freezer."],
 cons:"Frigo 3 giorni, non 4. Freezer 3 mesi.",par:"Bolle da solo.",think:"Perché il riso ha un giorno in meno? Leggi la domanda su Bacillus cereus nella Guida."},
{id:"couscous",name:"Couscous integrale al limone",role:"base",family:"frumento",portions:5,protein:7,kcal:198,prepMin:5,cookMin:5,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|couscous integrale|Dispensa","1|limone|Ortofrutta"]),steps:["Porta a bollore 330 ml d'acqua salata con un filo d'olio.","Versala sul couscous, copri e lascia 5 minuti.","Sgrana con una forchetta, aggiungi scorza e succo di limone."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Pronto in 5 minuti.",think:"Il couscous è semola di grano duro già precotta: per questo basta idratarlo."},
{id:"pasta",name:"Pasta integrale cotta in anticipo",role:"base",family:"frumento",portions:5,protein:7,kcal:187,prepMin:5,cookMin:12,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|pasta integrale|Dispensa"]),steps:["Cuoci la pasta 2 minuti meno del tempo in confezione.","Scolala, condiscila con un filo d'olio e stendila su un vassoio.","In frigo entro un'ora, in 5 porzioni.","Per scaldarla: in padella con il sugo e un cucchiaio d'acqua, o al microonde coperta."],
 cons:"Frigo 4 giorni. Freezer 2 mesi se al dente.",par:"Bolle da sola.",think:"Raffreddata e riscaldata ha più amido resistente: la retrogradazione dell'amido."},
{id:"pane",name:"Pane integrale",role:"base",family:"frumento",portions:5,protein:7,kcal:192,prepMin:0,cookMin:0,equip:"nessuno",fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["400 g|pane integrale|Panetteria"]),steps:["Taglialo a fette appena comprato: una porzione è circa 80 g.","Tieni fuori le fette per 2–3 giorni, il resto in freezer.","Le fette congelate si tostano direttamente."],
 cons:"Dispensa 3 giorni, freezer a fette 3 mesi.",par:"",think:""},
{id:"polenta",name:"Polenta a fette",role:"base",family:"mais",portions:5,protein:5,kcal:198,prepMin:5,cookMin:15,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|farina di mais per polenta|Dispensa"]),steps:["Porta a bollore 1,2 litri d'acqua salata.","Versa la farina a pioggia mescolando con la frusta; cuoci il tempo indicato (10 minuti l'istantanea, 40 la tradizionale).","Versala in una teglia rettangolare unta, livella a 2 cm e lasciala rapprendere.","Tagliala a fette: si scaldano in padella antiaderente o in forno finché fanno la crosticina."],
 cons:"Frigo 4 giorni, freezer a fette 3 mesi.",par:"La tradizionale è lunga: mescola ogni tanto mentre fai altro.",think:"Il mais non ha glutine ed è povero di lisina e triptofano: con i legumi nello stesso giorno il problema sparisce."},
{id:"saraceno",name:"Grano saraceno",role:"base",family:"saraceno",portions:5,protein:7,kcal:187,prepMin:5,cookMin:20,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|grano saraceno|Dispensa"]),steps:["Sciacqua il grano saraceno e tostalo 2 minuti in pentola asciutta: sa di nocciola.","Aggiungi acqua salata (due volte il suo volume), 15–20 minuti a fuoco basso col coperchio.","Sgrana, stendi a raffreddare, dividi in 5 porzioni."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Col coperchio, da solo.",think:"Non è un cereale ma un seme di una poligonacea, parente del rabarbaro: per questo non ha glutine."},
{id:"miglio",name:"Miglio",role:"base",family:"miglio",portions:5,protein:6,kcal:198,prepMin:5,cookMin:20,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|miglio|Dispensa"]),steps:["Sciacqua bene il miglio sotto l'acqua corrente (toglie il retrogusto amaro).","Tostalo 2 minuti, poi acqua salata (2,5 volte il volume) e coperchio: 20 minuti.","Sgrana con la forchetta, stendi a raffreddare."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Col coperchio, da solo.",think:""},
{id:"quinoa",name:"Quinoa",role:"base",family:"quinoa",portions:5,protein:8,kcal:203,prepMin:5,cookMin:15,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|quinoa|Dispensa"]),steps:["Sciacqua bene la quinoa in un colino (toglie le saponine amare).","Acqua salata doppia rispetto al volume, 15 minuti col coperchio.","Sgrana e stendi a raffreddare."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Col coperchio, da sola.",think:"È una delle poche fonti vegetali con tutti gli aminoacidi essenziali in buone proporzioni."},

{id:"bulgur",name:"Bulgur",role:"base",family:"frumento",portions:5,protein:7,kcal:190,prepMin:5,cookMin:12,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|bulgur|Dispensa"]),steps:["Porta a bollore acqua salata (due volte il volume del bulgur).","Versa il bulgur, 10–12 minuti a fuoco basso col coperchio, poi 5 minuti a fuoco spento.","Sgrana con la forchetta e stendi a raffreddare."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Pronto in un quarto d'ora.",think:"Il bulgur è grano duro precotto e spezzato: è frumento, come farro e couscous. Per variare davvero, abbinalo a un cereale di un'altra famiglia.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#C9A064",base2:"#B88E52",pieces:[{t:"grain",c:"#D6B27A",n:130,s:.028}]}},

{id:"pasta_lenticchie",name:"Pasta di lenticchie rosse",role:"base",family:"legumi",portions:5,protein:14,kcal:185,prepMin:5,cookMin:8,equip:"fuochi",fridgeDays:3,freezer:false,months:M("all"),
 ing:I(["275 g|pasta di lenticchie rosse|Dispensa"]),steps:["Cuocila 1–2 minuti meno del tempo in confezione: si sfalda più facilmente della pasta di grano.","Scolala delicatamente, condiscila subito con un filo d'olio perché non si incolli.","Stendila su un vassoio a raffreddare, poi in 5 porzioni.","Scaldala in padella col sugo, mescolando piano."],
 cons:"Frigo 3 giorni. In freezer diventa farinosa.",par:"Cuoce in pochi minuti.",think:"Conta come legume, non come cereale: quasi il doppio delle proteine della pasta di grano, ma senza glutine e con un sapore più deciso.",
 draw:{vessel:"plate",pieces:[{t:"penne",c:"#D9874A",n:28,s:.12}]}},
{id:"pasta_piselli",name:"Pasta di piselli",role:"base",family:"legumi",portions:5,protein:12,kcal:185,prepMin:5,cookMin:8,equip:"fuochi",fridgeDays:3,freezer:false,months:M("all"),
 ing:I(["275 g|pasta di piselli|Dispensa"]),steps:["Cuocila 1–2 minuti meno del tempo in confezione.","Scola con delicatezza e condisci subito con un filo d'olio.","Stendila a raffreddare e dividi in 5 porzioni."],
 cons:"Frigo 3 giorni.",par:"Cuoce in pochi minuti.",think:"Con un sugo di pomodoro e verdure fa da piatto unico: base e proteine insieme.",
 draw:{vessel:"plate",pieces:[{t:"penne",c:"#9DBB5A",n:28,s:.12}]}},
{id:"pasta_verdure",name:"Pasta agli spinaci, broccoli e basilico",role:"base",family:"frumento",portions:5,protein:7,kcal:190,prepMin:5,cookMin:11,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["275 g|pasta agli spinaci, broccoli e basilico|Dispensa"]),steps:["Cuocila 2 minuti meno del tempo in confezione.","Scola, filo d'olio, stendila a raffreddare.","Dividi in 5 porzioni."],
 cons:"Frigo 4 giorni, freezer 2 mesi al dente.",par:"Bolle da sola.",think:"Le verdure in polvere danno colore, ma in 55 g di pasta sono poche: per il conto delle piante resta frumento.",
 draw:{vessel:"plate",pieces:[{t:"penne",c:"#6E9A4A",n:28,s:.12}]}},

/* ---------- CONTORNI ---------- */
{id:"verd_aut",name:"Verdure d'autunno al forno",role:"side",portions:4,protein:4,kcal:170,prepMin:15,cookMin:40,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("9-12"),
 ing:I(["1 kg|zucca|Ortofrutta","1|cavolfiore|Ortofrutta","3|carote|Ortofrutta","2|cipolla rossa|Ortofrutta","2 cucchiai|olio EVO|Basi","2 rametti|rosmarino|Basi"]),
 steps:["Zucca a cubi di 2 cm, cavolfiore a cimette, carote a rondelle, cipolle a spicchi.","Condisci in una ciotola con olio, rosmarino, sale e paprika dolce.","Due teglie, un solo strato. 200 °C per 35–40 minuti, scambiando le teglie a metà."],
 cons:"Frigo 4 giorni. In freezer diventano molli.",par:"Prima cosa in forno.",think:"Verdure ammassate cuociono al vapore: la doratura (Maillard) vuole superficie asciutta e oltre 140 °C.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#E48A2A",n:20,s:.16},{t:"floret",c:"#EFE6CF",n:9,s:.15},{t:"round",c:"#E07A2B",inner:"#F0A35A",n:9,s:.1},{t:"ring",c:"#8E3B6A",n:8,s:.13}]}},
{id:"verd_inv",name:"Broccoli, finocchi e carote al forno",role:"side",portions:4,protein:5,kcal:140,prepMin:15,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("11-3"),
 ing:I(["600 g|broccoli|Ortofrutta","2|finocchi|Ortofrutta","3|carote|Ortofrutta","2 cucchiai|olio EVO|Basi"]),
 steps:["Broccoli a cimette, finocchi a spicchi, carote a bastoncini.","Olio, sale e origano.","200 °C per 30–35 minuti su due teglie."],
 cons:"Frigo 4 giorni.",par:"Prima cosa in forno.",think:"I broccoli contengono glucosinolati: la cottura breve al forno ne salva più della bollitura lunga.",
 draw:{vessel:"tray",pieces:[{t:"floret",c:"#3F7A35",n:14,s:.15},{t:"leafy",c:"#E9EFD8",n:8,s:.16},{t:"round",c:"#E07A2B",inner:"#F0A35A",n:10,s:.09}]}},
{id:"verd_est",name:"Verdure estive al forno",role:"side",portions:4,protein:3,kcal:115,prepMin:15,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["2|zucchine|Ortofrutta","2|peperoni|Ortofrutta","1|melanzana|Ortofrutta","1|cipolla rossa|Ortofrutta","2 cucchiai|olio EVO|Basi"]),
 steps:["Tutto a pezzi di 2–3 cm.","Olio, sale, origano.","200 °C per 30–35 minuti su due teglie."],
 cons:"Frigo 4 giorni.",par:"Prima cosa in forno.",think:"Le melanzane assorbono olio come spugne: condiscile per ultime, con meno olio del previsto.",
 draw:{vessel:"tray",pieces:[{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:12,s:.11},{t:"cube",c:"#D8402B",n:10,s:.14},{t:"cube",c:"#E8C33A",n:8,s:.14},{t:"cube",c:"#4A2C4F",n:8,s:.13}]}},
{id:"piselli",name:"Piselli e carote al cipollotto",role:"side",portions:4,protein:6,kcal:140,prepMin:10,cookMin:15,equip:"fuochi",fridgeDays:4,freezer:true,months:M("3-6"),
 ing:I(["450 g|piselli surgelati|Surgelati","2|carote|Ortofrutta","1 mazzo|cipollotti|Ortofrutta"]),
 steps:["Cipollotti a rondelle nell'olio, 3 minuti.","Carote a dadini e piselli, un bicchiere d'acqua, sale.","15 minuti col coperchio."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Fuoco libero, cuoce da solo.",think:"I piselli sono legumi: danno più proteine di qualsiasi altra verdura.",
 draw:{vessel:"plate",pieces:[{t:"dot",c:"#6FA84A",n:60,s:.03},{t:"cube",c:"#E07A2B",n:14,s:.06}]}},
{id:"slaw",name:"Insalata di cavolo cappuccio e carote",role:"side",portions:5,protein:2,kcal:75,prepMin:15,cookMin:0,equip:"nessuno",fridgeDays:5,freezer:false,months:M("10-4"),
 ing:I(["½|cavolo cappuccio|Ortofrutta","2|carote|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Affetta il cavolo sottilissimo, grattugia le carote.","Condisci con limone, olio e sale: il cavolo regge il condimento per giorni."],
 cons:"Frigo 5 giorni, anche già condita.",par:"Si fa a mano mentre tutto cuoce.",think:"Il cavolo crudo porta vitamina C: nello stesso pasto dei legumi aiuta ad assorbire il loro ferro.",
 draw:{vessel:"plate",pieces:[{t:"needle",c:"#E9EFD8",n:50,s:.12},{t:"needle",c:"#E8872E",n:30,s:.1}]}},
{id:"spinaci",name:"Spinaci ripassati all'aglio",role:"side",portions:4,protein:4,kcal:80,prepMin:10,cookMin:10,equip:"fuochi",fridgeDays:3,freezer:true,months:M("10-5"),
 ing:I(["800 g|spinaci freschi|Ortofrutta","2 spicchi|aglio|Ortofrutta"]),
 steps:["Lava gli spinaci e cuocili in padella solo con l'acqua rimasta sulle foglie, 3 minuti.","Strizza, poi ripassa con olio e aglio 5 minuti."],
 cons:"Frigo 3 giorni, freezer 3 mesi.",par:"Veloce, mentre sobbolle un'altra pentola.",think:"Tanto calcio sulla carta, poco assorbito: l'acido ossalico lo lega.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#2F5E28",n:30,s:.14}]}},
{id:"fagiolini",name:"Fagiolini al limone",role:"side",portions:4,protein:2,kcal:80,prepMin:10,cookMin:10,equip:"fuochi",fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["600 g|fagiolini|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Spunta i fagiolini.","Lessali 8–10 minuti in acqua salata, scolali e passali sotto acqua fredda.","Condisci con olio, limone e sale."],
 cons:"Frigo 4 giorni.",par:"Veloce, sul fuoco libero.",think:"L'acqua fredda ferma la cottura e fissa il verde: la clorofilla si degrada col calore prolungato.",
 draw:{vessel:"plate",pieces:[{t:"needle",c:"#4F8A3A",n:40,s:.2}]}},
{id:"insalata",name:"Insalata mista lavata per la settimana",role:"side",portions:4,protein:1,kcal:20,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["1 cespo|lattuga|Ortofrutta","1 cespo|radicchio|Ortofrutta"]),steps:["Lava le foglie, asciugale benissimo (centrifuga o canovaccio).","Contenitore con un foglio di carta da cucina sul fondo.","Condisci solo quando mangi."],
 cons:"Frigo 4 giorni se ben asciutta.",par:"Si fa a mano mentre tutto cuoce.",think:"Due insalate diverse invece di una: due piante in più nel conto della settimana, stesso lavoro.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#7DB257",n:20,s:.16},{t:"leafy",c:"#8E2A4A",n:10,s:.14}]}},
{id:"cetrioli",name:"Cetrioli e cipolla rossa all'aceto",role:"side",portions:4,protein:1,kcal:50,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:4,freezer:false,months:M("6-9"),
 ing:I(["2|cetrioli|Ortofrutta","1|cipolla rossa|Ortofrutta","3 cucchiai|aceto di mele|Basi"]),
 steps:["Cetrioli a rondelle sottili, cipolla a fettine.","Aceto, sale, un filo d'olio, aneto se ce l'hai. Niente zucchero.","Riposo in frigo: migliora dal giorno dopo."],
 cons:"Frigo 4 giorni.",par:"Zero fuochi.",think:"Questi sono sott'aceto, non fermentati: l'acido lo metti tu, non lo producono i batteri.",
 draw:{vessel:"plate",pieces:[{t:"round",c:"#4F8A3A",inner:"#DDE9C2",n:18,s:.13},{t:"ring",c:"#8E3B6A",n:8,s:.1}]}},
{id:"cavolo_nero",name:"Cavolo nero stufato con aglio e limone",role:"side",portions:4,protein:3,kcal:80,prepMin:10,cookMin:15,equip:"fuochi",fridgeDays:4,freezer:true,months:M("11-3"),
 ing:I(["500 g|cavolo nero|Ortofrutta","2 spicchi|aglio|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Togli la costa centrale e taglia le foglie a striscioline.","Aglio nell'olio, poi il cavolo e mezzo bicchiere d'acqua: 12–15 minuti col coperchio.","Scorza di limone alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Un fuoco, cuoce da solo.",think:"Tra le verdure è una delle fonti di calcio meglio assorbite, al contrario degli spinaci.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#243F22",n:24,s:.16}]}},

{id:"verd_stagione",name:"Verdure al forno di stagione",role:"side",seasonal:"forno",portions:4,protein:4,kcal:150,prepMin:15,cookMin:40,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["2 cucchiai|olio EVO|Basi","2 rametti|rosmarino|Basi"]),
 steps:["Taglia le verdure della settimana a pezzi simili (2–3 cm): quelle dure (zucca, carote, cavolfiore) un po' più piccole di quelle tenere (zucchine, peperoni).","Condisci in una ciotola con olio, rosmarino, sale e paprika dolce.","Due teglie, un solo strato. 200 °C per 30–40 minuti, scambiando le teglie a metà."],
 cons:"Frigo 4 giorni.",par:"Prima cosa in forno.",think:"Perché tagliare più piccole le verdure dure? Il calore deve arrivare al centro: meno spessore, cottura più breve, così finiscono tutte insieme.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#E48A2A",n:10,s:.15},{t:"floret",c:"#3F7A35",n:6,s:.14},{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:8,s:.1},{t:"cube",c:"#D8402B",n:6,s:.13},{t:"ring",c:"#8E3B6A",n:6,s:.12}]}},
{id:"insalata_stagione",name:"Insalata cruda di stagione",role:"side",seasonal:"crudo",portions:4,protein:2,kcal:45,prepMin:15,cookMin:0,equip:"nessuno",fridgeDays:3,freezer:false,months:M("all"),
 ing:I(["1|limone|Ortofrutta"]),
 steps:["Lava e asciuga benissimo le verdure della settimana.","Le foglie intere, le altre a julienne o grattugiate: tagliate sottili durano meno, quindi tienile in contenitori separati.","Condisci solo quando mangi, con olio, limone e sale."],
 cons:"Frigo 3 giorni, in contenitori separati e asciutti.",par:"Si fa a mano mentre tutto cuoce.",think:"Ogni verdura diversa è una pianta in più nel conto dei 30, allo stesso lavoro.",
 draw:{vessel:"plate",pieces:[{t:"leafy",c:"#7DB257",n:16,s:.15},{t:"needle",c:"#E8872E",n:16,s:.1},{t:"leafy",c:"#8E2A4A",n:8,s:.12}]}},
{id:"frit_stagione",name:"Frittata al forno di stagione",role:"main",seasonal:"frittata",portions:3,protein:25,kcal:310,prepMin:12,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["8|uova|Frigo","100 g|feta|Frigo"]),
 steps:["Cuoci le verdure della settimana: quelle tenere (zucchine, spinaci, funghi) crude a fette sottili, quelle dure (broccoli, carciofi, asparagi, porri) sbollentate 3–4 minuti.","Sbatti le uova con sale, pepe e la feta sbriciolata.","Teglia da 22 cm con carta forno unta: verdure, poi le uova. 180 °C per 25 minuti, finché il centro non trema."],
 cons:"Frigo 4 giorni. In freezer diventa acquosa.",par:"Sbollenta le verdure dure nell'acqua che bolle per il cereale.",think:"",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:8,s:.09},{t:"floret",c:"#3F7A35",n:5,s:.1},{t:"cube",c:"#F7F4EA",n:6,s:.06}]}},

/* ---------- PRINCIPALI ---------- */
{id:"merluzzo",name:"Merluzzo gratinato al limone",role:"main",portions:2,protein:34,kcal:290,prepMin:10,cookMin:15,equip:"forno",temp:200,fridgeDays:2,freezer:false,months:M("all"),
 ing:I(["400 g|filetti di merluzzo surgelati|Pesce","4 cucchiai|pangrattato|Dispensa","1 cucchiaio|parmigiano grattugiato|Frigo","½|limone|Ortofrutta","1 ciuffo|prezzemolo|Ortofrutta","1 spicchio|aglio|Ortofrutta"]),
 steps:["Scongela i filetti in un sacchetto chiuso a bagno in acqua fredda, 30–40 minuti.","Asciugali bene.","Panatura: pangrattato, parmigiano, prezzemolo, aglio, scorza di limone, olio.","200 °C per 12–15 minuti, finché si sfalda."],
 cons:"Frigo 2 giorni. Non congelare di nuovo.",par:"In forno insieme ad altro a 200 °C.",think:"Il merluzzo è magro: tante proteine ma pochi omega-3. Per quelli serve il pesce azzurro.",
 draw:{vessel:"plate",pieces:[{t:"fillet",c:"#F1EAD8",crumb:"#C98F3E",n:2,s:.5},{t:"wedge",c:"#F2D34A",n:1,s:.2}]}},
{id:"merluzzo_piselli",name:"Merluzzo in umido con piselli",role:"main",portions:3,protein:30,kcal:290,prepMin:10,cookMin:20,equip:"fuochi",fridgeDays:2,freezer:false,months:M("all"),
 ing:I(["450 g|filetti di merluzzo surgelati|Pesce","300 g|piselli surgelati|Surgelati","400 g|pelati|Dispensa","1|cipolla|Ortofrutta"]),
 steps:["Cipolla tritata nell'olio, 5 minuti.","Pelati e piselli, 10 minuti.","Adagia il merluzzo a pezzi (anche ancora semi-congelato), coperchio, 8–10 minuti."],
 cons:"Frigo 2 giorni.",par:"Un fuoco, cuoce da solo.",think:"Il sugo protegge il pesce dal seccarsi quando lo riscaldi.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#C4452C",base2:"#B03A24",pieces:[{t:"flake",c:"#F1EAD8",n:8,s:.2},{t:"dot",c:"#6FA84A",n:40,s:.028}]}},
{id:"polp_merluzzo",name:"Polpette di merluzzo e patate",role:"main",portions:4,protein:24,kcal:280,prepMin:20,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["400 g|filetti di merluzzo surgelati|Pesce","300 g|patate|Ortofrutta","1|uova|Frigo","30 g|parmigiano grattugiato|Frigo","60 g|pangrattato|Dispensa","1 ciuffo|prezzemolo|Ortofrutta"]),
 steps:["Lessa le patate a pezzi (15 min) e schiacciale.","Cuoci il merluzzo 5 minuti in acqua bollente, sbriciolalo.","Unisci tutto con uovo, parmigiano, prezzemolo e metà pangrattato.","Forma 20 polpette, passale nel pangrattato. 200 °C per 20 minuti."],
 cons:"Frigo 3 giorni. Freezer: prima sul vassoio, poi in sacchetto.",par:"Le patate lessano mentre il forno lavora.",think:"Pesce scongelato crudo non si ricongela; una volta cotto sì, perché la cottura abbatte la carica batterica.",
 draw:{vessel:"plate",pieces:[{t:"ball",c:"#D9A865",n:9,s:.13},{t:"wedge",c:"#F2D34A",n:1,s:.18}]}},
{id:"polp_tonno",name:"Polpette di tonno e ceci al forno",role:"main",portions:4,protein:26,kcal:340,prepMin:15,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["2 lattine|ceci|Dispensa","3 scatolette|tonno al naturale|Pesce","1|uova|Frigo","40 g|parmigiano grattugiato|Frigo","80 g|pangrattato|Dispensa","½|limone|Ortofrutta"]),
 steps:["Schiaccia i ceci sciacquati con una forchetta.","Unisci tonno, uovo, parmigiano, 50 g di pangrattato, scorza di limone, sale.","24 palline passate nel pangrattato rimasto.","200 °C per 20 minuti, girandole a metà."],
 cons:"Frigo 3 giorni. Freezer: prima sul vassoio 2 ore, poi in sacchetto.",par:"L'impasto si fa a mano mentre altro cuoce.",think:"Il tonno è un grande predatore e accumula più mercurio dello sgombro: meglio non tutti i giorni.",
 draw:{vessel:"plate",pieces:[{t:"ball",c:"#C98B45",n:9,s:.13},{t:"leafy",c:"#6FA84A",n:8,s:.12}]}},
{id:"polp_sgombro",name:"Polpette di sgombro e ceci",role:"main",portions:4,protein:26,kcal:370,prepMin:15,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,oily:true,months:M("all"),
 ing:I(["2 lattine|ceci|Dispensa","3 scatolette|sgombro al naturale|Pesce","1|uova|Frigo","60 g|pangrattato|Dispensa","1 ciuffo|prezzemolo|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Schiaccia i ceci sciacquati con una forchetta.","Unisci sgombro sgocciolato e sbriciolato, uovo, prezzemolo, scorza di limone, 40 g di pangrattato.","22 palline passate nel pangrattato rimasto.","200 °C per 20 minuti."],
 cons:"Frigo 3 giorni, freezer 3 mesi.",par:"Si impastano a mano mentre altro cuoce.",think:"Lo sgombro in scatola ha più di dieci volte gli omega-3 del merluzzo, e costa meno."},
{id:"sugo_sgombro",name:"Sugo di sgombro, capperi e olive",role:"main",portions:4,protein:17,kcal:210,prepMin:5,cookMin:20,equip:"fuochi",fridgeDays:3,freezer:true,oily:true,months:M("all"),
 ing:I(["3 scatolette|sgombro al naturale|Pesce","700 g|passata di pomodoro|Dispensa","1|cipolla|Ortofrutta","1 cucchiaio|capperi|Dispensa","10|olive nere|Dispensa"]),
 steps:["Cipolla e aglio nell'olio, 5 minuti.","Passata, sale e origano: 15 minuti.","Capperi, olive e sgombro a pezzi: altri 5 minuti.","Condisce la base della settimana: pasta, orzo, polenta o riso."],
 cons:"Frigo 3 giorni, freezer 3 mesi.",par:"Un fuoco, cuoce da solo.",think:"Lo sgombro è piccolo e ricco di omega-3, e costa molto meno del salmone.",
 draw:{vessel:"plate",pastaBed:"#B53A24",pieces:[{t:"penne",c:"#E9C27A",n:24,s:.12},{t:"flake",c:"#C9B59A",n:7,s:.09},{t:"olive",c:"#2A2322",n:6,s:.05}]}},
{id:"sardine",name:"Sardine gratinate al forno",role:"main",portions:3,protein:28,kcal:290,prepMin:20,cookMin:15,equip:"forno",temp:200,fridgeDays:2,freezer:false,oily:true,months:M("4-9"),
 ing:I(["700 g|sardine fresche|Pesce","4 cucchiai|pangrattato|Dispensa","1 ciuffo|prezzemolo|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Pulisci le sardine: testa via, apri a libro, togli la lisca (o chiedilo al banco).","Disponile in teglia, pelle sotto.","Pangrattato, prezzemolo, aglio, scorza di limone, olio. 200 °C per 12–15 minuti."],
 cons:"Frigo 2 giorni.",par:"In forno con altro a 200 °C.",think:"Pesce azzurro di stagione: costa poco perché se ne pesca tanto, e ha pochissimo mercurio.",
 draw:{vessel:"tray",pieces:[{t:"fillet",c:"#9FB3BF",crumb:"#C98F3E",n:2,s:.45}]}},
{id:"dahl",name:"Dahl di lenticchie rosse e spinaci",role:"main",portions:5,protein:21,kcal:390,prepMin:10,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["400 g|lenticchie rosse decorticate|Dispensa","1|cipolla|Ortofrutta","400 g|pelati|Dispensa","200 ml|latte di cocco|Dispensa","200 g|spinaci surgelati|Surgelati","1 cucchiaino|curcuma|Basi","1 cucchiaino|cumino|Basi"]),
 steps:["Cipolla e aglio nell'olio, 5 minuti.","Curcuma e cumino, un minuto. Niente peperoncino.","Lenticchie, pelati e 1,1 litri d'acqua: 25 minuti a fuoco basso.","Ultimi 5 minuti: spinaci e latte di cocco. Sala alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi. Si addensa: allunga con acqua.",par:"Sobbolle da solo.",think:"Una spruzzata di limone quando mangi: la vitamina C aiuta ad assorbire il ferro delle lenticchie.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#E1A133",base2:"#D48F24",pieces:[{t:"swirl",c:"#F6EBD8",n:2,s:.5},{t:"leafy",c:"#3B6E2E",n:10,s:.11}]}},
{id:"stufato",name:"Stufato di fagioli e lenticchie",role:"main",portions:4,protein:22,kcal:380,prepMin:10,cookMin:40,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["2 lattine|fagioli borlotti|Dispensa","200 g|lenticchie secche|Dispensa","800 g|pelati|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 cucchiaino|paprika dolce|Basi"]),
 steps:["Cipolla e carota tritate nell'olio, 5 minuti.","Paprika dolce e un pizzico di cumino, un minuto.","Lenticchie, pelati e 500 ml d'acqua: 30 minuti.","Aggiungi i borlotti sciacquati, altri 10 minuti. Sala."],
 cons:"Frigo 4 giorni, freezer 3 mesi: migliora il giorno dopo.",par:"Sobbolle da solo.",think:"Legumi e cereali nello stesso giorno coprono tutti gli aminoacidi essenziali.",
 draw:{vessel:"bowl",bowl:"#3A2E28",base:"#9E3A22",base2:"#8A2F1A",pieces:[{t:"flake",c:"#6B2F25",n:30,s:.06},{t:"dot",c:"#E8C33A",n:8,s:.02}]}},
{id:"lenticchie",name:"Lenticchie in umido",role:"main",portions:4,protein:19,kcal:330,prepMin:10,cookMin:35,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["300 g|lenticchie secche|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 costa|sedano|Ortofrutta","2 cucchiai|concentrato di pomodoro|Dispensa"]),
 steps:["Soffritto di cipolla, carota e sedano, 5 minuti.","Concentrato, lenticchie sciacquate, acqua a coprire di 3 dita.","35 minuti a fuoco basso, sala alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da solo.",think:"Perché salare alla fine? Il sale all'inizio può rallentare l'ammorbidimento della buccia di alcuni legumi.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#7A5A3A",base2:"#6B4C30",pieces:[{t:"grain",c:"#8B6A45",n:120,s:.03},{t:"cube",c:"#E07A2B",n:8,s:.05}]}},
{id:"cannellini_tonno",name:"Cannellini, tonno e cipolla rossa",role:"main",portions:3,protein:25,kcal:280,prepMin:10,cookMin:0,equip:"nessuno",fridgeDays:3,freezer:false,months:M("all"),
 ing:I(["2 lattine|fagioli cannellini|Dispensa","3 scatolette|tonno al naturale|Pesce","1|cipolla rossa|Ortofrutta","1 ciuffo|prezzemolo|Ortofrutta","1|limone|Ortofrutta"]),
 steps:["Cipolla a fettine sottili, 10 minuti in acqua e aceto per addolcirla.","Unisci cannellini sciacquati, tonno, prezzemolo, limone, olio e sale."],
 cons:"Frigo 3 giorni. Non si congela.",par:"Zero fuochi: si fa mentre tutto cuoce.",think:"Perché mettere la cipolla in acqua e aceto? L'acido neutralizza parte dei composti solforati pungenti.",
 draw:{vessel:"plate",pieces:[{t:"leaf",c:"#F3EEDD",n:40,s:.08},{t:"flake",c:"#C9B59A",n:8,s:.1},{t:"ring",c:"#8E3B6A",n:6,s:.1}]}},
{id:"frit_zucchine",name:"Frittata al forno con zucchine e feta",role:"main",portions:3,protein:24,kcal:310,prepMin:10,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("5-10"),
 ing:I(["8|uova|Frigo","100 g|feta|Frigo","2|zucchine|Ortofrutta","1 ciuffo|menta|Ortofrutta"]),
 steps:["Sbatti le uova con sale, pepe e menta tritata.","Teglia da 22 cm con carta forno unta, zucchine a rondelle sottili, feta sbriciolata.","Versa le uova. 180 °C per 25 minuti, finché il centro non trema."],
 cons:"Frigo 4 giorni. In freezer diventa acquosa.",par:"Di solito ultimo giro di forno, a 180 °C.",think:"Buona fredda: niente riscaldamento, niente frittata secca.",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"round",c:"#4F8A3A",inner:"#D9E6A8",n:14,s:.09},{t:"cube",c:"#F7F4EA",n:8,s:.06}]}},
{id:"frit_broccoli",name:"Frittata al forno con broccoli e tofu",role:"main",portions:3,protein:27,kcal:300,prepMin:15,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("10-4"),
 ing:I(["8|uova|Frigo","150 g|tofu naturale|Frigo","20 g|parmigiano grattugiato|Frigo","300 g|broccoli|Ortofrutta"]),
 steps:["Cimette di broccoli sbollentate 3 minuti.","Frulla il tofu con due uova fino a una crema, poi sbatti con le altre, parmigiano, sale.","Teglia da 22 cm unta: broccoli e uova. 180 °C per 25 minuti."],
 cons:"Frigo 4 giorni.",par:"Sbollenta i broccoli nell'acqua che bolle per il cereale.",think:"Il tofu frullato rende la frittata morbida come la ricotta, con più proteine.",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"floret",c:"#3F7A35",n:10,s:.12}]}},
{id:"frit_asparagi",name:"Frittata al forno con asparagi e ricotta",role:"main",portions:3,protein:26,kcal:320,prepMin:10,cookMin:25,equip:"forno",temp:180,fridgeDays:4,freezer:false,months:M("4-5"),
 ing:I(["8|uova|Frigo","150 g|ricotta|Frigo","20 g|parmigiano grattugiato|Frigo","400 g|asparagi|Ortofrutta"]),
 steps:["Togli la parte legnosa degli asparagi, tagliali a tocchetti.","Sbatti uova, ricotta, parmigiano e sale.","Teglia unta, asparagi, uova. 180 °C per 25 minuti."],
 cons:"Frigo 4 giorni.",par:"Ultimo giro di forno.",think:"",
 draw:{vessel:"pan",base:"#F0C94A",base2:"#E4B537",slices:4,pieces:[{t:"needle",c:"#4F8A3A",n:14,s:.22}]}},
{id:"torta_spinaci",name:"Torta salata di tofu e spinaci",role:"main",portions:4,protein:23,kcal:400,prepMin:15,cookMin:40,equip:"forno",temp:180,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["1 rotolo|pasta brisé|Frigo","300 g|tofu naturale|Frigo","3|uova|Frigo","450 g|spinaci surgelati|Surgelati","30 g|parmigiano grattugiato|Frigo"]),
 steps:["Spinaci scongelati e strizzati benissimo.","Frulla il tofu con le uova, unisci spinaci, parmigiano, sale e noce moscata.","Stendi la brisé nella teglia, bucherella, versa il ripieno.","180 °C per 40 minuti."],
 cons:"Frigo 3 giorni, freezer a fette 2 mesi.",par:"Lunga in forno: mettila presto.",think:"Perché strizzare gli spinaci? L'acqua in eccesso bagna la brisé da sotto e non cuoce.",
 draw:{vessel:"pan",base:"#D9A865",base2:"#2F5E28",slices:6,pieces:[{t:"leafy",c:"#2F5E28",n:20,s:.1}]}},
{id:"tofu",name:"Tofu al forno con soia e sesamo",role:"main",portions:3,protein:20,kcal:240,prepMin:10,cookMin:25,equip:"forno",temp:200,fridgeDays:4,freezer:false,months:M("all"),
 ing:I(["400 g|tofu naturale|Frigo","3 cucchiai|salsa di soia|Dispensa","1 cucchiaio|semi di sesamo|Dispensa","1 cucchiaio|amido di mais|Dispensa"]),
 steps:["Tampona il tofu con carta, taglialo a cubi.","Condisci con soia e olio, poi spolvera con l'amido.","200 °C per 25 minuti, girando a metà. Sesamo alla fine."],
 cons:"Frigo 4 giorni. In freezer diventa spugnoso.",par:"In forno con altro a 200 °C.",think:"Guarda il coagulante in etichetta: col solfato di calcio (E516) il tofu è anche una buona fonte di calcio.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#E3C48C",n:26,s:.14},{t:"dot",c:"#F4EBD2",n:30,s:.012}]}},
{id:"tempeh",name:"Tempeh marinato al forno",role:"main",portions:3,protein:25,kcal:290,prepMin:10,cookMin:20,equip:"forno",temp:200,fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["400 g|tempeh|Frigo","3 cucchiai|salsa di soia|Dispensa","1|limone|Ortofrutta","2 cm|zenzero fresco|Ortofrutta","1 spicchio|aglio|Ortofrutta"]),
 steps:["Taglia il tempeh a fette di 1 cm e sbollentalo 8 minuti: toglie l'amarognolo e assorbe meglio la marinata.","Marinata: soia, succo di limone, zenzero grattugiato, aglio, un filo d'olio. Almeno 15 minuti.","Teglia con carta forno, 200 °C per 20 minuti, girando a metà."],
 cons:"Frigo 4 giorni, freezer 2 mesi.",par:"Marina mentre il forno lavora ad altro.",think:"Il tempeh è soia fermentata con un fungo (Rhizopus). Ma si mangia cotto: i microrganismi non sono più vivi, quindi non conta come fermentato del giorno.",
 draw:{vessel:"tray",pieces:[{t:"cube",c:"#C9A87A",n:14,s:.2},{t:"dot",c:"#7A5A3A",n:40,s:.015}]}},
{id:"seitan",name:"Seitan alla pizzaiola",role:"main",portions:3,protein:28,kcal:250,prepMin:10,cookMin:20,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["400 g|seitan|Frigo","400 g|pelati|Dispensa","1 cucchiaio|capperi|Dispensa","1 cucchiaino|origano|Basi","1 spicchio|aglio|Ortofrutta"]),
 steps:["Aglio nell'olio, poi pelati schiacciati, origano e capperi: 10 minuti.","Aggiungi il seitan a fette e cuoci altri 10 minuti col coperchio."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Un fuoco, cuoce da solo.",think:"Il seitan è glutine di frumento: tante proteine, ma per il conto delle piante è ancora frumento."},
{id:"peperoni_ripieni",name:"Peperoni ripieni di tonno e riso",role:"main",portions:3,protein:23,kcal:360,prepMin:20,cookMin:40,equip:"forno",temp:180,fridgeDays:3,freezer:true,withBase:true,months:M("7-9"),
 ing:I(["3|peperoni|Ortofrutta","150 g|riso|Dispensa","3 scatolette|tonno al naturale|Pesce","1|uova|Frigo","30 g|parmigiano grattugiato|Frigo","200 g|passata di pomodoro|Dispensa"]),
 steps:["Lessa il riso 10 minuti (resta indietro di cottura).","Mescola riso, tonno, uovo, parmigiano, un po' di passata.","Riempi i peperoni tagliati a metà, passata sul fondo della teglia.","180 °C per 40 minuti."],
 cons:"Frigo 3 giorni, freezer 2 mesi.",par:"Il riso lessa mentre pulisci i peperoni.",think:"Il cereale è già dentro: in quel pasto non serve la base.",
 draw:{vessel:"tray",pieces:[{t:"leafy",c:"#D8402B",n:6,s:.3},{t:"dot",c:"#F2E3C0",n:40,s:.02}]}},
{id:"parmigiana",name:"Parmigiana di melanzane leggera",role:"main",portions:4,protein:18,kcal:330,prepMin:25,cookMin:35,equip:"forno",temp:200,fridgeDays:4,freezer:true,months:M("7-9"),
 ing:I(["2|melanzana|Ortofrutta","500 g|passata di pomodoro|Dispensa","250 g|mozzarella|Frigo","50 g|parmigiano grattugiato|Frigo","1 vasetto|basilico|Ortofrutta"]),
 steps:["Melanzane a fette, spennellate d'olio, 200 °C per 15 minuti invece di friggerle.","Strati: passata, melanzane, mozzarella a dadini, parmigiano, basilico.","200 °C per 20 minuti."],
 cons:"Frigo 4 giorni, freezer 3 mesi: migliora riposando.",par:"Le melanzane vanno in forno mentre prepari il resto.",think:"",
 draw:{vessel:"tray",pieces:[{t:"leafy",c:"#B53A24",n:14,s:.25},{t:"dot",c:"#F4EFE2",n:30,s:.04},{t:"leaf",c:"#3F7D34",n:6,s:.07}]}},
{id:"zuppa_ceci",name:"Zuppa di ceci e cavolo nero",role:"main",portions:4,protein:18,kcal:300,prepMin:15,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("11-3"),
 ing:I(["3 lattine|ceci|Dispensa","300 g|cavolo nero|Ortofrutta","1|cipolla|Ortofrutta","1|carote|Ortofrutta","40 g|parmigiano grattugiato|Frigo"]),
 steps:["Soffritto di cipolla e carota.","Cavolo nero a striscioline senza costa centrale, 5 minuti.","Ceci e 1 litro d'acqua, 25 minuti. Frulla un terzo per renderla cremosa.","Parmigiano al momento di servire."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da sola.",think:"Il cavolo nero migliora dopo la prima gelata: il freddo trasforma parte dell'amido in zuccheri.",
 draw:{vessel:"bowl",bowl:"#5B4A3A",base:"#D9B97A",base2:"#C9A565",pieces:[{t:"leafy",c:"#243F22",n:14,s:.12},{t:"dot",c:"#E3C893",n:30,s:.035}]}},
{id:"vellutata_zucca",name:"Vellutata di zucca e lenticchie rosse",role:"main",portions:4,protein:17,kcal:275,prepMin:15,cookMin:25,equip:"fuochi",fridgeDays:4,freezer:true,months:M("9-1"),
 ing:I(["800 g|zucca|Ortofrutta","250 g|lenticchie rosse decorticate|Dispensa","1|cipolla|Ortofrutta","1 rametto|rosmarino|Basi"]),
 steps:["Cipolla e rosmarino nell'olio.","Zucca a cubi, lenticchie e 1,2 litri d'acqua: 25 minuti.","Frulla col minipimer, sala."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da sola.",think:"Le lenticchie rosse, senza buccia, si sciolgono e addensano: non servono patate.",
 draw:{vessel:"bowl",bowl:"#26394A",base:"#E8892E",base2:"#DB7A22",pieces:[{t:"swirl",c:"#F6EBD8",n:1,s:.5},{t:"dot",c:"#3F6B3A",n:12,s:.02}]}},

{id:"ragu_soia",name:"Ragù di soia granulare",role:"main",portions:5,protein:22,kcal:210,prepMin:15,cookMin:30,equip:"fuochi",fridgeDays:4,freezer:true,months:M("all"),
 ing:I(["200 g|soia granulare|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 costa|sedano|Ortofrutta","700 g|passata di pomodoro|Dispensa","2 cucchiai|salsa di soia|Dispensa"]),
 steps:["Copri la soia granulare con acqua bollente (o brodo vegetale) e lasciala 10 minuti; scolala e strizzala bene con le mani.","Trita cipolla, carota e sedano e soffriggi 8 minuti.","Aggiungi la soia e rosolala 5 minuti a fuoco vivo con la salsa di soia: deve asciugarsi e prendere colore.","Passata e un bicchiere d'acqua, 25 minuti a fuoco basso. Sala alla fine."],
 cons:"Frigo 4 giorni, freezer 3 mesi.",par:"Sobbolle da solo mentre fai altro.",think:"La soia granulare è farina di soia sgrassata ed estrusa: a secco ha circa 50 g di proteine ogni 100 g. Idratata triplica il peso, per questo 200 g bastano per 5 porzioni.",
 draw:{vessel:"bowl",bowl:"#3A2E28",base:"#A8452A",base2:"#93391F",pieces:[{t:"grain",c:"#8A5A3A",n:110,s:.03},{t:"cube",c:"#E07A2B",n:6,s:.05}]}},
{id:"polp_soia",name:"Polpette di soia granulare e spinaci",role:"main",portions:4,protein:21,kcal:245,prepMin:20,cookMin:20,equip:"forno",temp:200,fridgeDays:3,freezer:true,months:M("all"),
 ing:I(["120 g|soia granulare|Dispensa","300 g|spinaci surgelati|Surgelati","1|uova|Frigo","30 g|parmigiano grattugiato|Frigo","70 g|pangrattato|Dispensa","1 spicchio|aglio|Ortofrutta"]),
 steps:["Idrata la soia in acqua bollente 10 minuti, poi strizzala benissimo.","Scongela e strizza gli spinaci, tritali.","Impasta soia, spinaci, uovo, parmigiano, aglio grattugiato, sale e 40 g di pangrattato.","20 polpette passate nel pangrattato rimasto, teglia unta, 200 °C per 20 minuti girandole a metà."],
 cons:"Frigo 3 giorni, freezer 3 mesi: prima sul vassoio, poi in sacchetto.",par:"L'impasto si fa a mano mentre altro cuoce.",think:"Perché strizzare tanto la soia? Trattiene acqua come una spugna: se resta bagnata, le polpette si sfaldano in forno.",
 draw:{vessel:"plate",pieces:[{t:"ball",c:"#8E6A3A",n:9,s:.13},{t:"leafy",c:"#2F5E28",n:6,s:.1}]}},

/* ---------- SCORTE DA FREEZER ---------- */
{id:"s_ragu_lenticchie",name:"Ragù di lenticchie",role:"scorta",portions:8,protein:10,kcal:180,prepMin:15,cookMin:45,equip:"fuochi",freezerMonths:3,months:M("all"),uses:"pasta, riso, polenta, patate al forno",
 ing:I(["300 g|lenticchie secche|Dispensa","1|cipolla|Ortofrutta","1|carote|Ortofrutta","1 costa|sedano|Ortofrutta","700 g|passata di pomodoro|Dispensa"]),
 steps:["Trita finissimi cipolla, carota e sedano; soffriggi 8 minuti.","Lenticchie sciacquate, passata e 600 ml d'acqua.","45 minuti a fuoco basso, finché è denso come un ragù.","Dividi in 8 porzioni in sacchetti stesi piatti."],
 cons:"Freezer 3 mesi. Scongelato, frigo 3 giorni.",par:"Sobbolle a lungo da solo.",think:"Perché congelare in sacchetti piatti? Più superficie: congela e scongela molto più in fretta."},
{id:"s_sugo_tonno",name:"Sugo di tonno, capperi e olive",role:"scorta",portions:6,protein:15,kcal:115,prepMin:5,cookMin:20,equip:"fuochi",freezerMonths:3,months:M("all"),uses:"pasta, riso, orzo",
 ing:I(["6 scatolette|tonno al naturale|Pesce","700 g|passata di pomodoro|Dispensa","1|cipolla|Ortofrutta","1 cucchiaio|capperi|Dispensa","10|olive nere|Dispensa"]),
 steps:["Cipolla nell'olio, 5 minuti.","Passata e origano, 15 minuti.","Tonno, capperi e olive: 3 minuti. Dividi in 6 porzioni."],
 cons:"Freezer 3 mesi. Scongelato, frigo 2 giorni.",par:"Un fuoco.",think:""},
{id:"s_pomodoro",name:"Sugo di pomodori freschi e basilico",role:"scorta",portions:8,protein:2,kcal:85,prepMin:20,cookMin:40,equip:"fuochi",freezerMonths:6,months:M("7-9"),uses:"pasta, riso, legumi, uova, base per altri sughi",
 ing:I(["2 kg|pomodori maturi|Ortofrutta","1|cipolla|Ortofrutta","1 vasetto|basilico|Ortofrutta"]),
 steps:["Incidi a croce i pomodori, 1 minuto in acqua bollente, pelali e tagliali.","Cipolla nell'olio, poi i pomodori: 40 minuti a fuoco basso.","Basilico alla fine. Porzioni in vasetti o sacchetti."],
 cons:"Freezer 6 mesi.",par:"Sobbolle da solo.",think:"Ad agosto i pomodori costano meno e sanno di più: la scorta congela anche il prezzo."},
{id:"s_pesto_basilico",name:"Pesto di basilico e semi di girasole",role:"scorta",portions:10,protein:2,kcal:150,prepMin:15,cookMin:0,equip:"nessuno",freezerMonths:6,months:M("6-9"),uses:"pasta, riso, legumi, patate, minestrone",
 ing:I(["2 vasetti|basilico|Ortofrutta","60 g|semi di girasole|Dispensa","30 g|parmigiano grattugiato|Frigo","1 spicchio|aglio|Ortofrutta","120 ml|olio EVO|Basi"]),
 steps:["Frulla basilico, semi, parmigiano, aglio e sale con l'olio a filo.","Riempi uno stampo per cubetti di ghiaccio, copri con un velo d'olio.","Una volta congelati, passa i cubetti in un sacchetto."],
 cons:"Freezer 6 mesi a cubetti. Un cubetto = una porzione.",par:"Zero fuochi.",think:"Il velo d'olio impedisce all'aria di toccare il basilico: niente ossidazione, niente pesto nero."},
{id:"s_pesto_cavolo",name:"Pesto di cavolo nero e noci",role:"scorta",portions:10,protein:3,kcal:140,prepMin:15,cookMin:5,equip:"fuochi",freezerMonths:6,months:M("11-3"),uses:"pasta, orzo, farro, bruschette, zuppe",
 ing:I(["300 g|cavolo nero|Ortofrutta","50 g|noci|Dispensa","30 g|parmigiano grattugiato|Frigo","1 spicchio|aglio|Ortofrutta","100 ml|olio EVO|Basi"]),
 steps:["Togli la costa al cavolo nero, sbollentalo 4 minuti, strizzalo.","Frulla con noci, parmigiano, aglio, sale e l'olio a filo.","Cubetti in freezer come il pesto di basilico."],
 cons:"Freezer 6 mesi a cubetti.",par:"Sbollenta nell'acqua già calda di un cereale.",think:"Le noci sono tra le poche fonti vegetali di omega-3 (ALA): utili, anche se il corpo ne converte poco in EPA e DHA."},
{id:"s_pesto_rucola",name:"Pesto di rucola e mandorle",role:"scorta",portions:10,protein:2,kcal:130,prepMin:10,cookMin:0,equip:"nessuno",freezerMonths:6,months:[4,5,6,9,10],uses:"pasta, riso, cereali, legumi",
 ing:I(["100 g|rucola|Ortofrutta","50 g|mandorle|Dispensa","30 g|parmigiano grattugiato|Frigo","100 ml|olio EVO|Basi"]),
 steps:["Frulla rucola, mandorle, parmigiano e sale con l'olio a filo.","Cubetti in freezer."],
 cons:"Freezer 6 mesi a cubetti.",par:"Zero fuochi.",think:"La rucola è amara perché contiene glucosinolati, gli stessi di cavoli e broccoli."},
{id:"s_crema_zucca",name:"Crema di zucca e ceci",role:"scorta",portions:8,protein:5,kcal:110,prepMin:15,cookMin:25,equip:"fuochi",freezerMonths:3,months:M("9-12"),uses:"pasta, riso, orzo, come vellutata allungata",
 ing:I(["1 kg|zucca|Ortofrutta","2 lattine|ceci|Dispensa","1|cipolla|Ortofrutta","1 rametto|rosmarino|Basi"]),
 steps:["Cipolla e rosmarino nell'olio.","Zucca a cubi e un bicchiere d'acqua, 20 minuti col coperchio.","Aggiungi i ceci, 5 minuti, frulla tutto. Porzioni da 150 g."],
 cons:"Freezer 3 mesi.",par:"Un fuoco.",think:""},
{id:"s_crema_piselli",name:"Crema di piselli e menta",role:"scorta",portions:8,protein:6,kcal:110,prepMin:10,cookMin:15,equip:"fuochi",freezerMonths:3,months:M("3-6"),uses:"pasta, riso, crostini, con uova sode",
 ing:I(["900 g|piselli surgelati|Surgelati","1 mazzo|cipollotti|Ortofrutta","1 ciuffo|menta|Ortofrutta"]),
 steps:["Cipollotti nell'olio, 3 minuti.","Piselli e un bicchiere d'acqua, 12 minuti.","Frulla con la menta e un filo d'olio. Porzioni da 150 g."],
 cons:"Freezer 3 mesi.",par:"Un fuoco.",think:""},
{id:"s_peperoni",name:"Sugo di peperoni dolci",role:"scorta",portions:8,protein:2,kcal:70,prepMin:15,cookMin:35,equip:"fuochi",freezerMonths:6,months:M("7-9"),uses:"pasta, riso, legumi, uova",
 ing:I(["1 kg|peperoni|Ortofrutta","400 g|pelati|Dispensa","1|cipolla|Ortofrutta"]),
 steps:["Peperoni a listarelle, cipolla a fettine.","Stufa in padella con olio, coperchio, 20 minuti.","Pelati, altri 15 minuti. Frulla metà per renderlo cremoso."],
 cons:"Freezer 6 mesi.",par:"Un fuoco.",think:"Peperoni dolci, niente peperoncino: il rosso viene dai carotenoidi, non dalla capsaicina."},

/* ---------- FERMENTATI ---------- */
{id:"f_crauti",name:"Crauti fatti in casa",role:"fermento",portions:25,protein:1,kcal:10,prepMin:30,cookMin:0,equip:"nessuno",fermDays:21,fridgeMonths:6,months:M("10-4"),salt:"2% del peso del cavolo",
 ing:I(["1 kg|cavolo cappuccio|Ortofrutta","20 g|sale grosso|Basi","1 cucchiaino|semi di cumino|Basi"]),
 steps:["Togli le foglie esterne (tienine una intera), taglia il cavolo a striscioline sottili e pesalo.","Aggiungi il 2% di sale sul peso (20 g per 1 kg) e i semi di cumino.","Massaggia con le mani 5–10 minuti: il cavolo si ammorbidisce e fa uscire il suo liquido.","Pressalo in un barattolo pulito fino a che il liquido lo copre del tutto. Sopra la foglia intera e un peso.","Coperchio appoggiato (o da aprire ogni giorno), 18–22 °C, al buio.","Assaggia dopo 1 settimana. Quando è acidulo come piace a te (2–4 settimane), in frigo."],
 cons:"In frigo fino a 6 mesi, sempre sommersi nel loro liquido e con posate pulite.",par:"Si prepara quando vuoi: non serve la domenica.",think:"Perché non serve aggiungere batteri? Sono già sulle foglie: il sale e l'assenza d'aria selezionano i lattobacilli, che tollerano entrambi meglio di muffe e putrefattivi."},
{id:"f_carote",name:"Carote in salamoia all'aneto",role:"fermento",portions:12,protein:0,kcal:15,prepMin:15,cookMin:0,equip:"nessuno",fermDays:7,fridgeMonths:3,months:M("all"),salt:"2,5% (25 g per litro d'acqua)",
 ing:I(["500 g|carote|Ortofrutta","25 g|sale grosso|Basi","2 spicchi|aglio|Ortofrutta","1 mazzetto|aneto|Ortofrutta"]),
 steps:["Sciogli 25 g di sale in 1 litro d'acqua (non serve bollirla se è buona da bere).","Carote a bastoncini, in piedi e strette in un barattolo con aglio e aneto.","Copri con la salamoia fino a 2 cm sopra, poi un peso che le tenga sotto.","5–10 giorni a 18–22 °C: la salamoia si intorbidisce e fa bollicine. Poi in frigo."],
 cons:"Frigo 3 mesi.",par:"",think:"La salamoia torbida è un buon segno: sono i lattobacilli al lavoro."},
{id:"f_cetrioli",name:"Cetrioli in salamoia",role:"fermento",portions:12,protein:0,kcal:10,prepMin:15,cookMin:0,equip:"nessuno",fermDays:5,fridgeMonths:2,months:M("6-9"),salt:"3,5% (35 g per litro d'acqua)",
 ing:I(["600 g|cetrioli|Ortofrutta","35 g|sale grosso|Basi","2 spicchi|aglio|Ortofrutta","1 mazzetto|aneto|Ortofrutta","3|foglie di alloro|Basi"]),
 steps:["Cetrioli piccoli e sodi, lavati, senza la punta del fiore (contiene enzimi che li ammorbidiscono).","Nel barattolo con aglio, aneto e alloro (i tannini li tengono croccanti).","Salamoia al 3,5%, un peso sopra. 4–7 giorni a temperatura ambiente, poi frigo."],
 cons:"Frigo 2 mesi.",par:"",think:"Perché qui il sale è più alto che per le carote? I cetrioli sono pieni d'acqua e la diluiscono."},
{id:"f_kimchi",name:"Kimchi bianco, non piccante",role:"fermento",portions:15,protein:1,kcal:15,prepMin:30,cookMin:0,equip:"nessuno",fermDays:4,fridgeMonths:2,months:M("10-3"),salt:"2% (20 g per litro d'acqua)",
 ing:I(["1|cavolo cinese|Ortofrutta","1|pere|Ortofrutta","1|carote|Ortofrutta","1 mazzo|cipollotti|Ortofrutta","3 spicchi|aglio|Ortofrutta","2 cm|zenzero fresco|Ortofrutta","20 g|sale grosso|Basi"]),
 steps:["Cavolo cinese a pezzi di 3 cm, salato con un cucchiaio di sale per 2 ore; poi sciacqua e scola.","Frulla pera, aglio e zenzero con 1 litro d'acqua e 20 g di sale: è la salamoia.","Nel barattolo: cavolo, carota a fiammiferi, cipollotti. Copri con la salamoia e metti un peso.","3–5 giorni a temperatura ambiente, poi frigo: continua a maturare piano."],
 cons:"Frigo 2 mesi.",par:"",think:"Il baek kimchi è la versione coreana senza peperoncino: il gusto viene dalla pera e dalla fermentazione."},
{id:"f_cavolfiore",name:"Cavolfiore e carote in salamoia",role:"fermento",portions:15,protein:1,kcal:15,prepMin:15,cookMin:0,equip:"nessuno",fermDays:8,fridgeMonths:3,months:M("10-4"),salt:"2,5% (25 g per litro d'acqua)",
 ing:I(["1|cavolfiore|Ortofrutta","2|carote|Ortofrutta","2 spicchi|aglio|Ortofrutta","25 g|sale grosso|Basi","3|foglie di alloro|Basi"]),
 steps:["Cavolfiore a cimette piccole, carote a rondelle.","Nel barattolo con aglio e alloro, salamoia al 2,5% fino a coprire, un peso sopra.","7–10 giorni a temperatura ambiente, poi frigo."],
 cons:"Frigo 3 mesi.",par:"",think:""},

/* ---------- DOLCI (zero zuccheri aggiunti) ---------- */
{id:"d_crema_nocciole",name:"Crema di nocciole e cacao fatta in casa",role:"dolce",portions:17,protein:2,kcal:98,sugar:0,prepMin:10,cookMin:0,equip:"nessuno",store:{dispensa:21,frigo:60,freezer:0},months:M("all"),
 ing:I(["200 g|crema 100% nocciole|Dispensa","30 g|cacao amaro|Dispensa","30 ml|olio EVO|Basi","q.b.|stevia|Dispensa","1 pizzico|sale|Basi"]),
 steps:["Mescola la crema di nocciole (a temperatura ambiente, così è fluida) con il cacao setacciato.","Aggiungi l'olio a filo continuando a mescolare fino a una crema lucida. Un olio EVO delicato, non piccante.","Dolcifica con la stevia poco alla volta e assaggia: quella in polvere pura è 200–300 volte più dolce dello zucchero, basta una punta di cucchiaino.","Un pizzico di sale esalta il cacao. Versa in un barattolo pulito e asciutto."],
 cons:"Dispensa 3 settimane in barattolo chiuso, frigo 2 mesi (si indurisce: tirala fuori 20 minuti prima). Se l'olio affiora, rimescola.",par:"Zero fuochi.",think:"Perché si conserva fuori frigo? Non contiene acqua: senza acqua libera i microbi non riescono a crescere. Se ci aggiungessi bevanda di soia, durerebbe pochi giorni in frigo.",
 draw:{vessel:"bowl",bowl:"#2F5F66",base:"#5A3524",base2:"#4A2A1C",pieces:[{t:"swirl",c:"#7A4A30",n:2,s:.5},{t:"dot",c:"#C99A5A",n:8,s:.03}]}},
{id:"d_barrette",name:"Barrette di avena e datteri",role:"dolce",portions:12,protein:6,kcal:190,sugar:0,prepMin:15,cookMin:20,equip:"forno",temp:170,store:{dispensa:7,frigo:14,freezer:3},months:M("all"),
 ing:I(["200 g|fiocchi d'avena|Dispensa","100 g|burro di arachidi|Dispensa","100 g|datteri|Dispensa","60 g|semi di girasole|Dispensa","30 g|cioccolato fondente 85%|Dispensa"]),
 steps:["Ammolla i datteri snocciolati 10 minuti in acqua calda, scolali e schiacciali in pasta con il burro di arachidi.","Unisci avena, semi, un pizzico di sale e il cioccolato tritato.","Pressa forte in una teglia 20×20 con carta forno.","170 °C per 20 minuti. Taglia in 12 solo quando è completamente fredda."],
 cons:"Dispensa 1 settimana in scatola ermetica, frigo 2 settimane, freezer 3 mesi.",par:"In forno quando è a 170–180 °C, insieme ad altro.",think:"I datteri addolciscono ma sono frutto intero, con la sua fibra: non sono zuccheri aggiunti."},
{id:"d_granola",name:"Granola croccante senza zucchero",role:"dolce",portions:12,protein:6,kcal:200,sugar:0,prepMin:10,cookMin:25,equip:"forno",temp:160,store:{dispensa:30,frigo:0,freezer:0},months:M("all"),
 ing:I(["300 g|fiocchi d'avena|Dispensa","80 g|mandorle|Dispensa","60 g|semi di zucca|Dispensa","60 g|datteri|Dispensa","40 ml|olio di semi|Dispensa"]),
 steps:["Frulla i datteri ammollati con 3 cucchiai d'acqua e l'olio: è il legante.","Mescola con avena, mandorle tritate, semi, cannella e sale.","Stendi su teglia, 160 °C per 25 minuti mescolando a metà.","Diventa croccante raffreddandosi: poi in barattolo."],
 cons:"Dispensa 1 mese in barattolo chiuso.",par:"Forno a 160 °C: meglio come ultimo giro.",think:"Con yogurt greco e frutta diventa una colazione da oltre 20 g di proteine."},
{id:"d_energy",name:"Palline di datteri e cacao",role:"dolce",portions:16,protein:2,kcal:85,sugar:0,prepMin:15,cookMin:0,equip:"nessuno",store:{dispensa:2,frigo:10,freezer:3},months:M("all"),
 ing:I(["200 g|datteri|Dispensa","100 g|fiocchi d'avena|Dispensa","60 g|burro di arachidi|Dispensa","20 g|cacao amaro|Dispensa"]),
 steps:["Ammolla i datteri snocciolati 10 minuti in acqua calda, scolali.","Schiacciali con la forchetta (o minipimer) con burro di arachidi e cacao.","Unisci l'avena, forma 16 palline."],
 cons:"Frigo 10 giorni, freezer 3 mesi.",par:"Zero fuochi.",think:""},
{id:"d_banana",name:"Banana bread senza zucchero",role:"dolce",portions:10,protein:5,kcal:195,sugar:0,prepMin:15,cookMin:45,equip:"forno",temp:180,store:{dispensa:3,frigo:6,freezer:3},months:M("all"),
 ing:I(["3|banane|Ortofrutta","220 g|farina integrale|Dispensa","50 ml|olio di semi|Dispensa","125 g|yogurt greco 0%|Frigo","80 ml|bevanda di soia|Frigo","1 bustina|lievito per dolci|Dispensa","50 g|noci|Dispensa"]),
 steps:["Schiaccia le banane molto mature (con la buccia nera).","Unisci olio, yogurt e bevanda di soia, poi farina, lievito, cannella e noci.","Stampo da plumcake con carta forno, 180 °C per 45 minuti (prova stecchino)."],
 cons:"Dispensa 3 giorni, frigo 6, freezer a fette 3 mesi.",par:"Lungo in forno: mettilo presto.",think:"Più la banana è nera, più amido si è trasformato in zucchero: per questo qui non serve aggiungerne."},
{id:"d_mele",name:"Torta di mele all'olio senza zucchero",role:"dolce",portions:10,protein:6,kcal:175,sugar:0,prepMin:20,cookMin:40,equip:"forno",temp:180,store:{dispensa:3,frigo:5,freezer:3},months:M("9-3"),
 ing:I(["3|mele|Ortofrutta","220 g|farina integrale|Dispensa","2|uova|Frigo","150 g|yogurt greco 0%|Frigo","60 ml|olio di semi|Dispensa","60 g|dolcificante eritritolo e stevia|Dispensa","1 bustina|lievito per dolci|Dispensa","1|limone|Ortofrutta"]),
 steps:["Sbatti uova e dolcificante, poi yogurt, olio e scorza di limone.","Farina e lievito setacciati, poi 2 mele a dadini.","Nello stampo, la terza mela a fettine sopra. 180 °C per 40 minuti."],
 cons:"Dispensa 3 giorni coperta, frigo 5, freezer a fette 3 mesi.",par:"In forno a 180 °C con la frittata o dopo.",think:"L'eritritolo è un poliolo quasi senza calorie che non alza la glicemia; a dosi alte può dare fastidi intestinali."},
{id:"d_muffin_pere",name:"Muffin pere e cacao",role:"dolce",portions:12,protein:4,kcal:130,sugar:0,prepMin:15,cookMin:22,equip:"forno",temp:180,store:{dispensa:3,frigo:5,freezer:3},months:M("9-2"),
 ing:I(["2|pere|Ortofrutta","200 g|farina integrale|Dispensa","25 g|cacao amaro|Dispensa","50 g|dolcificante eritritolo e stevia|Dispensa","50 ml|olio di semi|Dispensa","180 ml|bevanda di soia|Frigo","1|uova|Frigo","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Sbatti uovo e dolcificante, poi olio e bevanda di soia.","Aggiungi farina, cacao e lievito, poi le pere a dadini.","12 pirottini, 180 °C per 22 minuti."],
 cons:"Dispensa 3 giorni, freezer 3 mesi: si scongelano in un'ora.",par:"In forno a 180 °C.",think:""},
{id:"d_biscotti_zucca",name:"Biscotti morbidi di zucca e avena",role:"dolce",portions:20,protein:2,kcal:75,sugar:0,prepMin:15,cookMin:15,equip:"forno",temp:180,store:{dispensa:5,frigo:7,freezer:3},months:M("10-12"),
 ing:I(["200 g|zucca|Ortofrutta","180 g|fiocchi d'avena|Dispensa","100 g|farina integrale|Dispensa","40 g|dolcificante eritritolo e stevia|Dispensa","50 ml|olio di semi|Dispensa","½ bustina|lievito per dolci|Dispensa"]),
 steps:["Grattugia la zucca cruda finissima.","Mescola con olio, dolcificante, cannella, poi avena, farina e lievito.","20 mucchietti su teglia, 180 °C per 15 minuti."],
 cons:"Dispensa 5 giorni in latta, freezer 3 mesi.",par:"Usa un pezzo della zucca comprata per le verdure.",think:""},
{id:"d_plumcake_arancia",name:"Plumcake all'arancia e yogurt",role:"dolce",portions:10,protein:6,kcal:170,sugar:0,prepMin:15,cookMin:45,equip:"forno",temp:175,store:{dispensa:3,frigo:5,freezer:3},months:M("12-3"),
 ing:I(["2|arance|Ortofrutta","250 g|farina integrale|Dispensa","2|uova|Frigo","150 g|yogurt greco 0%|Frigo","70 g|dolcificante eritritolo e stevia|Dispensa","60 ml|olio di semi|Dispensa","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Scorza e succo delle arance (circa 150 ml).","Sbatti uova e dolcificante, poi succo, scorza, yogurt e olio, infine farina e lievito.","Stampo da plumcake, 175 °C per 45 minuti."],
 cons:"Dispensa 3 giorni, frigo 5, freezer a fette 3 mesi.",par:"Lungo in forno.",think:""},
{id:"d_barrette_fragole",name:"Barrette crumble alle fragole",role:"dolce",portions:10,protein:4,kcal:170,sugar:0,prepMin:15,cookMin:30,equip:"forno",temp:180,store:{dispensa:0,frigo:4,freezer:2},months:M("4-6"),
 ing:I(["250 g|fragole|Ortofrutta","200 g|fiocchi d'avena|Dispensa","100 g|farina integrale|Dispensa","60 ml|olio di semi|Dispensa","40 g|dolcificante eritritolo e stevia|Dispensa"]),
 steps:["Mescola avena, farina, dolcificante, olio e un pizzico di sale: deve sbriciolarsi.","Pressa due terzi in teglia, fragole a pezzi sopra, resto a briciole.","180 °C per 30 minuti. Taglia da fredda."],
 cons:"Frigo 4 giorni (la frutta è umida), freezer 2 mesi.",par:"In forno a 180 °C.",think:""},
{id:"d_muffin_albicocche",name:"Muffin alle albicocche e yogurt",role:"dolce",portions:12,protein:4,kcal:120,sugar:0,prepMin:15,cookMin:22,equip:"forno",temp:180,store:{dispensa:2,frigo:4,freezer:3},months:M("6-8"),
 ing:I(["4|albicocche|Ortofrutta","220 g|farina integrale|Dispensa","150 g|yogurt greco 0%|Frigo","1|uova|Frigo","60 g|dolcificante eritritolo e stevia|Dispensa","50 ml|olio di semi|Dispensa","1 bustina|lievito per dolci|Dispensa"]),
 steps:["Uovo, dolcificante, yogurt e olio.","Farina e lievito, poi le albicocche a dadini.","12 pirottini, 180 °C per 22 minuti."],
 cons:"Dispensa 2 giorni, frigo 4, freezer 3 mesi.",par:"In forno a 180 °C.",think:""},
{id:"d_bark",name:"Tavoletta gelata di yogurt greco e pesche",role:"dolce",portions:8,protein:7,kcal:80,sugar:0,prepMin:10,cookMin:0,equip:"nessuno",store:{dispensa:0,frigo:0,freezer:2},months:M("6-9"),
 ing:I(["500 g|yogurt greco 0%|Frigo","2|pesche|Ortofrutta","q.b.|stevia|Dispensa","50 g|fiocchi d'avena|Dispensa"]),
 steps:["Mescola lo yogurt con un pizzico di stevia, stendilo 1 cm su una teglia con carta forno.","Pesche a dadini e avena tostata sopra.","Freezer 3 ore, poi spezzala e tienila in un sacchetto."],
 cons:"Solo freezer, 2 mesi. Si mangia 5 minuti dopo averla tolta.",par:"Zero fuochi.",think:"Perché non diventa un blocco di ghiaccio duro? Proteine e solidi dello yogurt abbassano il punto di congelamento e ostacolano i cristalli grandi."}
].map(r=>({temp:0,needsBase:"",fav:false,photo:null,cons:"",par:"",think:"",dairy:false,spicy:false,fridgeDays:0,freezer:false,kcal:0,...r}));

/* Illustrazioni per le ricette che non ne hanno una propria */
const DRAW_EXTRA={
 couscous:{vessel:"bowl",bowl:"#2F5F66",base:"#E6CB84",base2:"#D8B76A",pieces:[{t:"dot",c:"#F0DA9C",n:160,s:.012},{t:"leaf",c:"#4E8A3A",n:5,s:.06}]},
 farro:{vessel:"bowl",bowl:"#2F5F66",base:"#C9A56C",base2:"#B58E55",pieces:[{t:"grain",c:"#D8B983",n:130,s:.035}]},
 orzo:{vessel:"bowl",bowl:"#5B4A3A",base:"#D9C7A0",base2:"#C8B288",pieces:[{t:"grain",c:"#EADBB8",n:120,s:.035}]},
 riso:{vessel:"bowl",bowl:"#3D4F5C",base:"#CDB893",base2:"#B9A27A",pieces:[{t:"grain",c:"#DCC9A4",n:140,s:.03}]},
 pasta:{vessel:"plate",pieces:[{t:"penne",c:"#C9A15E",n:28,s:.12}]},
 pane:{vessel:"plate",pieces:[{t:"cube",c:"#B07A43",n:3,s:.32}]},
 polenta:{vessel:"tray",pieces:[{t:"cube",c:"#F0C44A",n:10,s:.3}]},
 saraceno:{vessel:"bowl",bowl:"#5B4A3A",base:"#8A6A4A",base2:"#7A5A3A",pieces:[{t:"grain",c:"#9C7A55",n:120,s:.03}]},
 miglio:{vessel:"bowl",bowl:"#2F5F66",base:"#E8D48A",base2:"#DCC475",pieces:[{t:"dot",c:"#F2E2A0",n:160,s:.012}]},
 quinoa:{vessel:"bowl",bowl:"#3D4F5C",base:"#E3D2AE",base2:"#D6C29A",pieces:[{t:"dot",c:"#F0E4C8",n:150,s:.014},{t:"dot",c:"#9A3A2A",n:30,s:.012}]},
 polp_sgombro:{vessel:"plate",pieces:[{t:"ball",c:"#B98450",n:9,s:.13},{t:"wedge",c:"#F2D34A",n:1,s:.18}]},
 seitan:{vessel:"bowl",bowl:"#26394A",base:"#C4452C",base2:"#B03A24",pieces:[{t:"cube",c:"#B28A5E",n:10,s:.18},{t:"dot",c:"#5E7A2E",n:12,s:.02}]},
 s_ragu_lenticchie:{vessel:"bowl",bowl:"#3A2E28",base:"#8E3522",base2:"#7A2C1C",pieces:[{t:"grain",c:"#6B3A25",n:90,s:.03},{t:"cube",c:"#E07A2B",n:8,s:.05}]},
 s_sugo_tonno:{vessel:"bowl",bowl:"#26394A",base:"#C4452C",base2:"#B03A24",pieces:[{t:"flake",c:"#D9C4A5",n:14,s:.1},{t:"olive",c:"#2A2322",n:6,s:.045}]},
 s_pomodoro:{vessel:"bowl",bowl:"#2F5F66",base:"#D2412A",base2:"#BF3620",pieces:[{t:"leaf",c:"#3F7D34",n:5,s:.1}]},
 s_pesto_basilico:{vessel:"bowl",bowl:"#5B4A3A",base:"#4F8A2E",base2:"#3F7524",pieces:[{t:"dot",c:"#DCCB86",n:20,s:.018}]},
 s_pesto_cavolo:{vessel:"bowl",bowl:"#5B4A3A",base:"#2F4F2A",base2:"#26421F",pieces:[{t:"flake",c:"#B08A5A",n:10,s:.06}]},
 s_pesto_rucola:{vessel:"bowl",bowl:"#2F5F66",base:"#5C8F3A",base2:"#4C7C2E",pieces:[{t:"flake",c:"#E6D3B0",n:10,s:.05}]},
 s_crema_zucca:{vessel:"bowl",bowl:"#26394A",base:"#E8892E",base2:"#DB7A22",pieces:[{t:"dot",c:"#E3C893",n:14,s:.03}]},
 s_crema_piselli:{vessel:"bowl",bowl:"#5B4A3A",base:"#8DBE55",base2:"#7DAE45",pieces:[{t:"leaf",c:"#2F6B3A",n:5,s:.08},{t:"swirl",c:"#EEF3DE",n:1,s:.4}]},
 s_peperoni:{vessel:"bowl",bowl:"#2F5F66",base:"#D9542E",base2:"#C8461F",pieces:[{t:"needle",c:"#E8C33A",n:10,s:.12}]},
 f_crauti:{vessel:"bowl",bowl:"#3D4F5C",base:"#E8E2C0",base2:"#DAD3AA",pieces:[{t:"needle",c:"#F2EDD2",n:60,s:.12},{t:"dot",c:"#6B5A3A",n:20,s:.01}]},
 f_carote:{vessel:"bowl",bowl:"#2F5F66",base:"#E9E4CF",base2:"#DDD6BC",pieces:[{t:"needle",c:"#E8872E",n:24,s:.28},{t:"needle",c:"#4F8A3A",n:10,s:.1}]},
 f_cetrioli:{vessel:"bowl",bowl:"#2F5F66",base:"#E4E6CF",base2:"#D6D8BC",pieces:[{t:"round",c:"#4F7A2E",inner:"#C9DDA0",n:12,s:.16}]},
 f_kimchi:{vessel:"bowl",bowl:"#5B4A3A",base:"#EFEAD2",base2:"#E2DCC0",pieces:[{t:"leafy",c:"#DDE8B8",n:16,s:.16},{t:"needle",c:"#E8872E",n:12,s:.1},{t:"needle",c:"#4F8A3A",n:10,s:.08}]},
 f_cavolfiore:{vessel:"bowl",bowl:"#3D4F5C",base:"#E9E4CF",base2:"#DDD6BC",pieces:[{t:"floret",c:"#F2EAD2",n:10,s:.14},{t:"round",c:"#E07A2B",inner:"#F0A35A",n:8,s:.08}]},
 d_barrette:{vessel:"tray",pieces:[{t:"cube",c:"#C9955A",n:12,s:.28},{t:"dot",c:"#3A2418",n:30,s:.015}]},
 d_granola:{vessel:"bowl",bowl:"#2F5F66",base:"#D2A865",base2:"#C08F4C",pieces:[{t:"flake",c:"#B7843F",n:40,s:.06},{t:"dot",c:"#3F6B3A",n:12,s:.02}]},
 d_energy:{vessel:"plate",pieces:[{t:"ball",c:"#5A3524",n:10,s:.17}]},
 d_banana:{vessel:"tray",pieces:[{t:"cube",c:"#9A6A3A",n:6,s:.32},{t:"dot",c:"#F0D9A0",n:20,s:.02}]},
 d_mele:{vessel:"pan",base:"#D8A55A",base2:"#C9924A",slices:8,pieces:[{t:"leaf",c:"#F3E3A8",n:18,s:.14}]},
 d_muffin_pere:{vessel:"plate",pieces:[{t:"ball",c:"#4A2E22",n:6,s:.26}]},
 d_biscotti_zucca:{vessel:"plate",pieces:[{t:"ball",c:"#D9923E",n:9,s:.18}]},
 d_plumcake_arancia:{vessel:"tray",pieces:[{t:"cube",c:"#E0A64A",n:6,s:.32},{t:"needle",c:"#E8872E",n:10,s:.06}]},
 d_barrette_fragole:{vessel:"tray",pieces:[{t:"cube",c:"#D7B07A",n:12,s:.27},{t:"dot",c:"#C8303A",n:30,s:.025}]},
 d_muffin_albicocche:{vessel:"plate",pieces:[{t:"ball",c:"#E2A24A",n:6,s:.26},{t:"dot",c:"#F08A2A",n:10,s:.03}]},
 d_bark:{vessel:"tray",pieces:[{t:"flake",c:"#F4EFE2",n:14,s:.3},{t:"cube",c:"#F2A65A",n:14,s:.07}]},
 tempeh:{vessel:"tray",pieces:[{t:"cube",c:"#C9A87A",n:14,s:.2},{t:"dot",c:"#7A5A3A",n:40,s:.015}]}
};
LIB.forEach(r=>{if(!r.draw&&DRAW_EXTRA[r.id])r.draw=DRAW_EXTRA[r.id]});

/* ============ AGGIUNTE AI PASTI ============
 Usate quando un giorno resta sotto gli 80 g di proteine, o a mano. ferm = fermentato con microrganismi vivi */
const BOOSTERS=[
 {id:"uova",name:"2 uova sode",protein:12,kcal:150,ing:{q:"2",n:"uova",r:"Frigo"},prep:true},
 {id:"edamame",name:"Edamame",protein:11,kcal:120,ing:{q:"100 g",n:"edamame surgelati",r:"Surgelati"}},
 {id:"feta",name:"Feta",protein:6,kcal:105,ing:{q:"40 g",n:"feta",r:"Frigo"}},
 {id:"yogurt_greco",name:"Salsa di yogurt greco",protein:10,kcal:55,ferm:true,ing:{q:"100 g",n:"yogurt greco 0%",r:"Frigo"}},
 {id:"tofu_aff",name:"Tofu affumicato a cubetti",protein:10,kcal:95,ing:{q:"60 g",n:"tofu affumicato",r:"Frigo"}},
 {id:"parm",name:"Parmigiano",protein:7,kcal:78,ing:{q:"20 g",n:"parmigiano grattugiato",r:"Frigo"}},
 {id:"ceci",name:"Ceci",protein:7,kcal:120,ing:{q:"100 g",n:"ceci",r:"Dispensa"}},
 {id:"crauti",name:"Crauti o verdure fermentate",protein:0,kcal:10,ferm:true,home:true,ing:null},
 {id:"germogli",name:"Germogli nell'insalata",protein:1,kcal:10,ing:{q:"30 g",n:"germogli misti",r:"Ortofrutta"}},
 {id:"chia",name:"Semi di chia",protein:2,kcal:50,ing:{q:"10 g",n:"semi di chia",r:"Dispensa"}}
];

/* ============ FRUTTA DI STAGIONE ============ */
const FRUITS=[
 {id:"mela",label:"1 mela",n:"mele",q:"1",kcal:80,months:M("8-5"),pair:"con grana, burro di arachidi o noci"},
 {id:"pera",label:"1 pera",n:"pere",q:"1",kcal:85,months:M("8-2"),pair:"con grana o pecorino: l'abbinamento classico"},
 {id:"arancia",label:"1 arancia",n:"arance",q:"1",kcal:70,months:M("11-4"),pair:"con mandorle; la vitamina C aiuta il ferro dei legumi del pasto"},
 {id:"mandarini",label:"2 mandarini",n:"mandarini",q:"2",kcal:80,months:M("11-2"),pair:"con noci o con yogurt greco"},
 {id:"kiwi",label:"2 kiwi",n:"kiwi",q:"2",kcal:90,months:M("11-4"),pair:"con yogurt greco o kefir"},
 {id:"pompelmo",label:"½ pompelmo",n:"pompelmo",q:"½",kcal:40,months:M("12-4"),pair:"con yogurt e avena"},
 {id:"cachi",label:"1 caco",n:"cachi",q:"1",kcal:110,months:M("10-12"),pair:"con yogurt greco: è già dolce come un budino"},
 {id:"melograno",label:"½ melograno",n:"melograno",q:"½",kcal:80,months:M("10-12"),pair:"sui chicchi di yogurt o nel porridge"},
 {id:"uva",label:"150 g di uva",n:"uva",q:"150 g",kcal:100,months:M("8-10"),pair:"con mandorle o formaggio"},
 {id:"fichi",label:"150 g di fichi",n:"fichi",q:"150 g",kcal:100,months:M("8-9"),pair:"con ricotta o con noci"},
 {id:"prugne",label:"150 g di prugne",n:"prugne",q:"150 g",kcal:70,months:M("7-9"),pair:"con yogurt o kefir"},
 {id:"pesca",label:"1 pesca",n:"pesche",q:"1",kcal:60,months:M("6-9"),pair:"con yogurt greco o mandorle"},
 {id:"albicocche",label:"3 albicocche",n:"albicocche",q:"3",kcal:60,months:M("6-7"),pair:"con mandorle o ricotta"},
 {id:"ciliegie",label:"150 g di ciliegie",n:"ciliegie",q:"150 g",kcal:90,months:M("5-7"),pair:"con yogurt greco"},
 {id:"fragole",label:"150 g di fragole",n:"fragole",q:"150 g",kcal:45,months:M("4-6"),pair:"con yogurt o crema di nocciole"},
 {id:"nespole",label:"150 g di nespole",n:"nespole",q:"150 g",kcal:70,months:M("5-6"),pair:"con mandorle"},
 {id:"melone",label:"200 g di melone",n:"melone",q:"200 g",kcal:65,months:M("6-8"),pair:"con feta o yogurt"},
 {id:"anguria",label:"250 g di anguria",n:"anguria",q:"250 g",kcal:75,months:M("7-8"),pair:"con feta e menta"},
 {id:"fichi_india",label:"2 fichi d'India",n:"fichi d'India",q:"2",kcal:60,months:M("8-10"),pair:"con yogurt o ricotta; sbucciali con coltello e forchetta per le spine"},
 {id:"banana",label:"1 banana",n:"banane",q:"1",kcal:95,months:M("all"),auto:false,pair:"con burro di arachidi o nel porridge. Non è di stagione in Italia: viene da lontano tutto l'anno"},
 {id:"mirtilli",label:"125 g di mirtilli",n:"mirtilli",q:"125 g",kcal:70,months:M("6-9"),pair:"nello yogurt o nel porridge"}
];

/* ============ VERDURE DI STAGIONE (per le ricette che si adattano) ============
 forno / crudo / frittata = quantità per la ricetta (4 porzioni di contorno, 3 di frittata) */
const SEASONAL_VEG=[
 {n:"zucca",months:M("9-1"),forno:"600 g"},
 {n:"cavolfiore",months:M("10-3"),forno:"½"},
 {n:"broccoli",months:M("10-3"),forno:"500 g",frittata:"300 g"},
 {n:"cavolini di Bruxelles",months:M("11-2"),forno:"400 g"},
 {n:"finocchi",months:M("10-4"),forno:"2",crudo:"1"},
 {n:"porri",months:M("10-3"),forno:"2",frittata:"1"},
 {n:"carciofi",months:M("11-4"),forno:"4",frittata:"3"},
 {n:"radicchio",months:M("10-3"),forno:"1",crudo:"1"},
 {n:"cavolo cappuccio",months:M("10-4"),crudo:"¼"},
 {n:"valeriana",months:M("10-4"),crudo:"125 g"},
 {n:"spinaci freschi",months:M("10-5"),frittata:"300 g"},
 {n:"asparagi",months:M("4-5"),forno:"400 g",frittata:"400 g"},
 {n:"ravanelli",months:M("3-6"),crudo:"1 mazzo"},
 {n:"cipollotti",months:M("3-6"),frittata:"1 mazzo",crudo:"1 mazzo"},
 {n:"rucola",months:[4,5,6,9,10],crudo:"125 g"},
 {n:"lattuga",months:M("4-10"),crudo:"1 cespo"},
 {n:"zucchine",months:M("5-9"),forno:"2",frittata:"2",crudo:"1"},
 {n:"peperoni",months:M("6-9"),forno:"2",crudo:"1"},
 {n:"melanzana",months:M("6-9"),forno:"1"},
 {n:"pomodori",months:M("6-9"),crudo:"300 g"},
 {n:"cetrioli",months:M("6-9"),crudo:"1"},
 {n:"barbabietole precotte",months:M("5-11"),crudo:"250 g"},
 {n:"carote",months:M("all"),forno:"3",crudo:"2"},
 {n:"cipolla rossa",months:M("all"),forno:"1"},
 {n:"funghi champignon",months:M("all"),forno:"300 g",frittata:"250 g"}
];
/* Stagionalità di frutta e verdura fresche, per il controllo delle ricette tue */
const PRODUCE_SEASON={};
SEASONAL_VEG.forEach(v=>{if(v.months.length<12)PRODUCE_SEASON[v.n]=v.months});
FRUITS.forEach(f=>{PRODUCE_SEASON[f.n]=f.months});
Object.assign(PRODUCE_SEASON,{"pomodori maturi":M("7-9"),"pomodorini":M("6-9"),"cavolo cinese":M("10-3"),"cavolo nero":M("11-3"),"verza":M("10-3"),"fagiolini":M("6-9"),"fave":M("4-6"),"piselli freschi":M("4-6"),"spinaci":M("10-5"),"bietole":M("10-5"),"cime di rapa":M("11-3"),"sedano rapa":M("10-3"),"topinambur":M("11-3"),"castagne":M("10-12"),"cachi":M("10-12"),"melone":M("6-8"),"anguria":M("7-8"),"fragole":M("4-6"),"ciliegie":M("5-7"),"albicocche":M("6-7"),"pesche":M("6-9"),"mandarini":M("11-2"),"arance":M("11-4"),"kiwi":M("11-4"),"pompelmo":M("12-4"),"limone":M("all")});

/* ============ COLAZIONI E SPUNTINI ============
 kcal e proteine senza la frutta (si aggiunge a parte). ferm = fermentato vivo. needs = serve un dolce fatto in casa */
const SNACKS=[
 {id:"c_yogurt",type:"colazione",name:"Yogurt greco, avena, noci e frutta",kcal:275,protein:22,fruit:true,ferm:true,
  ing:I(["170 g|yogurt greco 0%|Frigo","30 g|fiocchi d'avena|Dispensa","10 g|noci|Dispensa"]),why:"Proteine alte già a colazione: la sazietà dura fino a pranzo."},
 {id:"c_porridge",type:"colazione",name:"Porridge con bevanda di soia, semi e frutta",kcal:275,protein:15,fruit:true,
  ing:I(["40 g|fiocchi d'avena|Dispensa","200 ml|bevanda di soia|Frigo","10 g|semi di zucca|Dispensa"]),why:"I beta-glucani dell'avena rallentano l'assorbimento degli zuccheri della frutta."},
 {id:"c_porridge_avena",type:"colazione",name:"Porridge con bevanda d'avena, chia e frutta",kcal:290,protein:10,fruit:true,
  ing:I(["40 g|fiocchi d'avena|Dispensa","200 ml|bevanda di avena|Frigo","10 g|semi di chia|Dispensa"]),why:"Più cremoso di quello con la soia, ma con meno proteine: abbinalo a uno spuntino proteico."},
 {id:"c_uova",type:"colazione",name:"Pane integrale tostato, 2 uova sode e frutta",kcal:300,protein:18,fruit:true,eggs:2,
  ing:I(["60 g|pane integrale|Panetteria","2|uova|Frigo"]),why:"Colazione salata: le uova sode si preparano la domenica e durano 7 giorni col guscio."},
 {id:"c_kefir",type:"colazione",name:"Kefir con avena, noci e frutta",kcal:300,protein:12,fruit:true,ferm:true,
  ing:I(["200 ml|kefir|Frigo","30 g|fiocchi d'avena|Dispensa","10 g|noci|Dispensa"]),why:"Il kefir contiene più specie di microrganismi dello yogurt."},
 {id:"c_crema",type:"colazione",name:"Pane integrale con crema di nocciole fatta in casa e yogurt greco",kcal:318,protein:20,fruit:false,ferm:true,needs:"d_crema_nocciole",
  ing:I(["60 g|pane integrale|Panetteria","125 g|yogurt greco 0%|Frigo"]),why:"Il dolce della mattina, senza zucchero aggiunto."},
 {id:"s_yogurt",type:"spuntino",name:"Yogurt greco e frutta",kcal:100,protein:17,fruit:true,ferm:true,
  ing:I(["170 g|yogurt greco 0%|Frigo"]),why:"Il modo più semplice per aggiungere 17 g di proteine e un fermentato."},
 {id:"s_yogurt_magro",type:"spuntino",name:"Yogurt magro bianco, semi di chia e frutta",kcal:115,protein:9,fruit:true,ferm:true,
  ing:I(["150 g|yogurt magro bianco|Frigo","10 g|semi di chia|Dispensa"]),why:"Lo yogurt magro ha meno della metà delle proteine del greco: i semi di chia aggiungono fibre e omega-3 vegetali."},
 {id:"s_yogurt_soia",type:"spuntino",name:"Yogurt di soia, semi di zucca e frutta",kcal:120,protein:8,fruit:true,ferm:true,
  ing:I(["125 g|yogurt di soia|Frigo","10 g|semi di zucca|Dispensa"]),why:"Scegli quello con fermenti vivi e senza zuccheri aggiunti."},
 {id:"s_kefir",type:"spuntino",name:"Kefir e frutta",kcal:125,protein:7,fruit:true,ferm:true,
  ing:I(["200 ml|kefir|Frigo"]),why:"Fermentato e dissetante."},
 {id:"s_noci",type:"spuntino",name:"Frutta e noci",kcal:100,protein:2,fruit:true,
  ing:I(["15 g|noci|Dispensa"]),why:"Grassi e fibre rallentano lo zucchero della frutta; le noci portano omega-3 vegetali."},
 {id:"s_mandorle",type:"spuntino",name:"Frutta e mandorle",kcal:120,protein:4,fruit:true,
  ing:I(["20 g|mandorle|Dispensa"]),why:"Le mandorle sono tra la frutta secca più ricca di calcio."},
 {id:"s_grana",type:"spuntino",name:"Frutta e grana",kcal:98,protein:8,fruit:true,
  ing:I(["25 g|parmigiano grattugiato|Frigo"]),why:"Proteine e calcio; il sapore salato bilancia il dolce della frutta."},
 {id:"s_arachidi",type:"spuntino",name:"Frutta e burro di arachidi",kcal:90,protein:4,fruit:true,
  ing:I(["15 g|burro di arachidi|Dispensa"]),why:"Scegli quello 100% arachidi, senza zucchero né oli aggiunti."},
 {id:"s_uovo",type:"spuntino",name:"Uovo sodo e frutta",kcal:75,protein:7,fruit:true,eggs:1,
  ing:I(["1|uova|Frigo"]),why:"Si prepara la domenica con le altre uova sode: 7 giorni in frigo col guscio."},
 {id:"s_edamame",type:"spuntino",name:"Edamame con un pizzico di sale",kcal:120,protein:11,fruit:false,
  ing:I(["100 g|edamame surgelati|Surgelati"]),why:"Spuntino salato con tante proteine: si scongelano in 3 minuti in acqua bollente."},
 {id:"s_hummus",type:"spuntino",name:"Hummus con carote e finocchi crudi",kcal:200,protein:6,fruit:false,
  ing:I(["60 g|hummus|Frigo","1|carote|Ortofrutta","½|finocchi|Ortofrutta"]),why:"Due verdure crude in più nel conto della settimana."},
 {id:"s_ricotta",type:"spuntino",name:"Ricotta, cannella e frutta",kcal:140,protein:9,fruit:true,
  ing:I(["100 g|ricotta|Frigo"]),why:"Con fichi o pere diventa un dessert."},
 {id:"s_barretta",type:"spuntino",name:"Barretta di avena e datteri fatta in casa",kcal:190,protein:6,fruit:false,needs:"d_barrette",
  ing:[],why:"Dalla scorta di dolci."}
];

/* ============ OBIETTIVI ============ */
const KCAL_TARGET=1800, PROT_MIN=80, PROT_MAX=100, MEAL_PROT_MIN=55, PLANTS_TARGET=30;

/* ============ PIANTE (per il conto dell'American Gut Project) ============
 Ingrediente -> specie vegetale. Frumento conta una volta sola qualunque sia la forma. */
const PLANT={
 "farro perlato":"frumento","couscous integrale":"frumento","pasta integrale":"frumento","pane integrale":"frumento","farina integrale":"frumento","seitan":"frumento","pasta brisé":"frumento",
 "orzo perlato":"orzo","riso integrale":"riso","riso":"riso","farina di mais per polenta":"mais","grano saraceno":"grano saraceno","miglio":"miglio","quinoa":"quinoa","fiocchi d'avena":"avena",
 "ceci":"ceci","hummus":"ceci","lenticchie rosse decorticate":"lenticchie","lenticchie secche":"lenticchie","fagioli borlotti":"fagioli","fagioli cannellini":"fagioli","piselli surgelati":"piselli",
 "tofu naturale":"soia","tofu affumicato":"soia","tempeh":"soia","edamame surgelati":"soia","bevanda di soia":"soia","yogurt di soia":"soia",
 "noci":"noci","mandorle":"mandorle","semi di chia":"chia","germogli misti":"germogli","soia granulare":"soia","pasta di lenticchie rosse":"lenticchie","pasta di piselli":"piselli","pasta agli spinaci, broccoli e basilico":"frumento","bulgur":"frumento","bevanda di avena":"avena","yogurt magro bianco":null,"crema 100% nocciole":"nocciole","burro di arachidi":"arachidi","semi di zucca":"semi di zucca","semi di girasole":"girasole","semi di sesamo":"sesamo",
 "latte di cocco":"cocco","datteri":"datteri","cacao amaro":"cacao","cioccolato fondente 85%":"cacao","olive nere":"olive","capperi":"capperi",
 "pelati":"pomodoro","passata di pomodoro":"pomodoro","concentrato di pomodoro":"pomodoro","pomodori maturi":"pomodoro",
 "spinaci surgelati":"spinaci","spinaci freschi":"spinaci","cipolla rossa":"cipolla","cipolla":"cipolla","cipollotti":"cipolla","zucca":"zucca","patate":"patata",
 "lattuga":"lattuga","radicchio":"radicchio","cavolo cappuccio":"cavolo cappuccio","cavolo cinese":"cavolo cinese","cavolo nero":"cavolo nero","cavolfiore":"cavolfiore","broccoli":"broccoli",
 "zenzero fresco":"zenzero","limone":"limone","prezzemolo":"prezzemolo","basilico":"basilico","menta":"menta","aneto":"aneto","rucola":"rucola"
};
Object.assign(PLANT,{"rosmarino":"rosmarino","curcuma":"curcuma","cumino":"cumino","semi di cumino":"cumino","paprika dolce":"paprika","origano":"origano","foglie di alloro":"alloro","aglio":"aglio"});
const HERBS=new Set(["prezzemolo","basilico","menta","aneto","zenzero","capperi","cacao","rosmarino","curcuma","cumino","paprika","origano","alloro"]);
